<?php

// @generated by bin/console generate. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Tests\Generator\Shared;

use Nesk\Puphpeteer\RemoteObject;

class GeneratedFixture extends RemoteObject
{
    /**
     * @param array{timeout?: int}|null $options
     */
    public function select(string $selector, ?array $options = null): string
    {
        return $this->invokeRemote('$', func_get_args());
    }

    public function evaluate(string $expression, mixed ...$arguments): mixed
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $arguments));
    }
}
