<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Closure;
use Nesk\Puphpeteer\JsFunction;
use Nesk\Puphpeteer\RemoteObject;

class BrowserContext extends RemoteObject
{
    public function browser(): Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function clearPermissionOverrides(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function close(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    public bool $closed {
        get {
            return $this->getRemote('closed');
        }
    }

    /**
     * @return list<array{domain: string, expires: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, partitionKeyOpaque?: bool, path: string, priority?: "Low"|"Medium"|"High", sameSite?: "Strict"|"Lax"|"None"|"Default", secure: bool, session: bool, size: int|float, sourceScheme?: "Unset"|"NonSecure"|"Secure", value: string}>
     */
    public function cookies(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{domain: string, expires: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, partitionKeyOpaque?: bool, path: string, priority?: "Low"|"Medium"|"High", sameSite?: "Strict"|"Lax"|"None"|"Default", secure: bool, session: bool, size: int|float, sourceScheme?: "Unset"|"NonSecure"|"Secure", value: string} ...$cookies
     */
    public function deleteCookie(mixed ...$cookies): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $cookies));
    }

    /**
     * @param array{domain?: string, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, path?: string, url?: string} ...$filters
     */
    public function deleteMatchingCookies(mixed ...$filters): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $filters));
    }
    public ?string $id {
        get {
            return $this->getRemote('id');
        }
    }

    public function listenerCount(string $type): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{type?: "tab", background?: bool}|array{type: "window", windowBounds?: array{height?: int|float, left?: int|float, top?: int|float, width?: int|float, windowState?: "normal"|"minimized"|"maximized"|"fullscreen"}, background?: bool})|null $options
     */
    public function newPage(?array $options = null): Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (Closure|JsFunction)|null $handler
     */
    public function off(string $type, Closure|JsFunction|null $handler = null): BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function on(string $type, Closure|JsFunction $handler): BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function once(string $type, Closure|JsFunction $handler): BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param list<"accelerometer"|"ambient-light-sensor"|"background-sync"|"camera"|"clipboard-read"|"clipboard-sanitized-write"|"clipboard-write"|"geolocation"|"gyroscope"|"idle-detection"|"keyboard-lock"|"magnetometer"|"microphone"|"midi-sysex"|"midi"|"notifications"|"payment-handler"|"persistent-storage"|"pointer-lock"> $permissions
     */
    public function overridePermissions(string $origin, array $permissions): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (bool)|null $includeAll
     *
     * @return list<Page>
     */
    public function pages(?bool $includeAll = null): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (string)|null $type
     */
    public function removeAllListeners(?string $type = null): BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{domain: string, expires?: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, path?: string, priority?: "Low"|"Medium"|"High", sameSite?: "Strict"|"Lax"|"None"|"Default", secure?: bool, sourceScheme?: "Unset"|"NonSecure"|"Secure", value: string} ...$cookies
     */
    public function setCookie(mixed ...$cookies): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $cookies));
    }

    /**
     * @param array{permission: array{allowWithoutSanitization?: bool, name: string, panTiltZoom?: bool, sysex?: bool, userVisibleOnly?: bool}, state: "granted"|"denied"|"prompt"} ...$permissions
     */
    public function setPermission(string $origin, mixed ...$permissions): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $permissions));
    }

    /**
     * @return list<Target>
     */
    public function targets(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param Closure(Target):bool                              $predicate
     * @param (array{signal?: never, timeout?: int|float})|null $options
     */
    public function waitForTarget(Closure $predicate, ?array $options = null): Target
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
