<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Closure;
use Nesk\Puphpeteer\JsFunction;
use Nesk\Puphpeteer\RemoteObject;

class Browser extends RemoteObject
{
    /**
     * @param array{colorDepth?: int|float, devicePixelRatio?: int|float, height: int|float, isInternal?: bool, label?: string, left: int|float, rotation?: int|float, top: int|float, width: int|float, workAreaInsets?: array{bottom?: int|float, left?: int|float, right?: int|float, top?: int|float}} $params
     *
     * @return array{availHeight: int|float, availLeft: int|float, availTop: int|float, availWidth: int|float, colorDepth: int|float, devicePixelRatio: int|float, height: int|float, id: string, isExtended: bool, isInternal: bool, isPrimary: bool, label: string, left: int|float, orientation: array{angle: int|float, type: string}, top: int|float, width: int|float}
     */
    public function addScreen(array $params): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return list<BrowserContext>
     */
    public function browserContexts(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function close(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    public bool $connected {
        get {
            return $this->getRemote('connected');
        }
    }

    /**
     * @return list<array{domain: string, expires: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, partitionKeyOpaque?: bool, path: string, priority?: "Low"|"Medium"|"High", sameSite?: "Strict"|"Lax"|"None"|"Default", secure: bool, session: bool, size: int|float, sourceScheme?: "Unset"|"NonSecure"|"Secure", value: string}>
     */
    public function cookies(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{downloadBehavior?: array{downloadPath?: string, policy: "default"|"allow"|"deny"|"allowAndName"}, proxyBypassList?: list<string>, proxyServer?: string})|null $options
     */
    public function createBrowserContext(?array $options = null): BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function defaultBrowserContext(): BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{domain: string, expires: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, partitionKeyOpaque?: bool, path: string, priority?: "Low"|"Medium"|"High", sameSite?: "Strict"|"Lax"|"None"|"Default", secure: bool, session: bool, size: int|float, sourceScheme?: "Unset"|"NonSecure"|"Secure", value: string} ...$cookies
     */
    public function deleteCookie(mixed ...$cookies): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $cookies));
    }

    /**
     * @param array{domain?: string, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, path?: string, url?: string} ...$filters
     */
    public function deleteMatchingCookies(mixed ...$filters): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $filters));
    }

    public function disconnect(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{manifestId: string} $options
     *
     * @return array{badgeCount: int|float, fileHandlers: list<array{accepts: list<array{fileExtensions: list<string>, mediaType: string}>, action: string, displayName: string}>}
     */
    public function getPWAState(array $options): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return array{height?: int|float, left?: int|float, top?: int|float, width?: int|float, windowState?: "normal"|"minimized"|"maximized"|"fullscreen"}
     */
    public function getWindowBounds(string $windowId): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{enabledInIncognito: bool})|null $options
     */
    public function installExtension(string $path, ?array $options = null): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{displayMode?: "browser"|"standalone", installUrlOrBundleUrl: string, manifestId: string} $options
     */
    public function installPWA(array $options): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{manifestId: string, timeout?: int|float, url?: string} $options
     */
    public function launchPWA(array $options): Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function listenerCount(string $type): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{type?: "tab", background?: bool}|array{type: "window", windowBounds?: array{height?: int|float, left?: int|float, top?: int|float, width?: int|float, windowState?: "normal"|"minimized"|"maximized"|"fullscreen"}, background?: bool})|null $options
     */
    public function newPage(?array $options = null): Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (Closure|JsFunction)|null $handler
     */
    public function off(string $type, Closure|JsFunction|null $handler = null): Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function on(string $type, Closure|JsFunction $handler): Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function once(string $type, Closure|JsFunction $handler): Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (bool)|null $includeAll
     *
     * @return list<Page>
     */
    public function pages(?bool $includeAll = null): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (string)|null $type
     */
    public function removeAllListeners(?string $type = null): Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function removeScreen(string $screenId): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return list<array{availHeight: int|float, availLeft: int|float, availTop: int|float, availWidth: int|float, colorDepth: int|float, devicePixelRatio: int|float, height: int|float, id: string, isExtended: bool, isInternal: bool, isPrimary: bool, label: string, left: int|float, orientation: array{angle: int|float, type: string}, top: int|float, width: int|float}>
     */
    public function screens(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{domain: string, expires?: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, path?: string, priority?: "Low"|"Medium"|"High", sameSite?: "Strict"|"Lax"|"None"|"Default", secure?: bool, sourceScheme?: "Unset"|"NonSecure"|"Secure", value: string} ...$cookies
     */
    public function setCookie(mixed ...$cookies): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $cookies));
    }

    /**
     * @param array{permission: array{allowWithoutSanitization?: bool, name: string, panTiltZoom?: bool, sysex?: bool, userVisibleOnly?: bool}, state: "denied"|"granted"|"prompt"} ...$permissions
     */
    public function setPermission(string $origin, mixed ...$permissions): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $permissions));
    }

    /**
     * @param array{height?: int|float, left?: int|float, top?: int|float, width?: int|float, windowState?: "normal"|"minimized"|"maximized"|"fullscreen"} $windowBounds
     */
    public function setWindowBounds(string $windowId, array $windowBounds): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function target(): Target
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return list<Target>
     */
    public function targets(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function uninstallExtension(string $id): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{manifestId: string} $options
     */
    public function uninstallPWA(array $options): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function userAgent(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function version(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param Closure(Target):bool                              $predicate
     * @param (array{signal?: never, timeout?: int|float})|null $options
     */
    public function waitForTarget(Closure $predicate, ?array $options = null): Target
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function wsEndpoint(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
