<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Closure;
use Nesk\Puphpeteer\JsFunction;
use Nesk\Puphpeteer\RemoteObject;

class CDPSession extends RemoteObject
{
    public function connection(): ?Connection
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function detach(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    public bool $detached {
        get {
            return $this->getRemote('detached');
        }
    }

    public function id(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function listenerCount(string $type): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (Closure|JsFunction)|null $handler
     */
    public function off(string $type, Closure|JsFunction|null $handler = null): CDPSession
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function on(string $type, Closure|JsFunction $handler): CDPSession
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function once(string $type, Closure|JsFunction $handler): CDPSession
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (string)|null $type
     */
    public function removeAllListeners(?string $type = null): CDPSession
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
