<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Closure;
use Nesk\Puphpeteer\JsFunction;
use Nesk\Puphpeteer\RemoteObject;

class Connection extends RemoteObject
{
    /**
     * @param array{attached: bool, browserContextId?: string, canAccessOpener: bool, embedderData?: mixed, openerFrameId?: string, openerId?: string, parentFrameId?: string, parentId?: string, subtype?: string, targetId: string, title: string, type: string, url: string} $targetInfo
     */
    public function createSession(array $targetInfo): CDPSession
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function dispose(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function listenerCount(string $type): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (Closure|JsFunction)|null $handler
     */
    public function off(string $type, Closure|JsFunction|null $handler = null): Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function on(string $type, Closure|JsFunction $handler): Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function once(string $type, Closure|JsFunction $handler): Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (string)|null $type
     */
    public function removeAllListeners(?string $type = null): Connection
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function session(string $sessionId): ?CDPSession
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    public int|float $timeout {
        get {
            return $this->getRemote('timeout');
        }
    }

    public function url(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function fromSession(CDPSession $session): ?Connection
    {
        return $this->invokeStaticRemote(__FUNCTION__, func_get_args());
    }
}
