<?php

// @generated by bin/console generate. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Nesk\Puphpeteer\RemoteObject;

class ConsoleMessage extends RemoteObject
{
    /**
     * @return list<JSHandle>
     */
    public function args(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return array{columnNumber?: int|float, lineNumber?: int|float, url?: string}
     */
    public function location(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return list<array{columnNumber?: int|float, lineNumber?: int|float, url?: string}>
     */
    public function stackTrace(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function text(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return "error"|"clear"|"table"|"dir"|"assert"|"info"|"warn"|"count"|"log"|"debug"|"dirxml"|"trace"|"startGroup"|"startGroupCollapsed"|"endGroup"|"profile"|"profileEnd"|"timeEnd"|"verbose"
     */
    public function type(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
