<?php

// @generated by bin/console generate. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Nesk\Puphpeteer\RemoteObject;

class Coverage extends RemoteObject
{
    /**
     * @param (array{resetOnNavigation?: bool})|null $options
     */
    public function startCSSCoverage(?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{includeRawScriptCoverage?: bool, reportAnonymousScripts?: bool, resetOnNavigation?: bool, useBlockCoverage?: bool})|null $options
     */
    public function startJSCoverage(?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return list<array{ranges: list<array{start: int|float, end: int|float}>, text: string, url: string}>
     */
    public function stopCSSCoverage(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return list<array{ranges: list<array{start: int|float, end: int|float}>, rawScriptCoverage?: array{functions: list<array{functionName: string, isBlockCoverage: bool, ranges: list<array{count: int|float, endOffset: int|float, startOffset: int|float}>}>, scriptId: string, url: string}, text: string, url: string}>
     */
    public function stopJSCoverage(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
