<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Nesk\Puphpeteer\RemoteObject;

class Dialog extends RemoteObject
{
    /**
     * @param (string)|null $promptText
     */
    public function accept(?string $promptText = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function defaultValue(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function dismiss(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    public bool $handled {
        get {
            return $this->getRemote('handled');
        }
    }

    public function message(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return "prompt"|"alert"|"confirm"|"beforeunload"
     */
    public function type(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
