<?php

// @generated by bin/console generate. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Nesk\Puphpeteer\JsFunction;
use Override;

class ElementHandle extends JSHandle
{
    /**
     * @return ElementHandle|null
     */
    public function querySelector(mixed $selector): mixed
    {
        return $this->invokeRemote('$', func_get_args());
    }

    /**
     * @param (array{isolate: bool})|null $options
     *
     * @return list<ElementHandle>
     */
    public function querySelectorAll(mixed $selector, ?array $options = null): mixed
    {
        return $this->invokeRemote('$$', func_get_args());
    }

    public function querySelectorAllEval(mixed $selector, string|JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote('$$eval', self::mergeNamedArguments(func_get_args(), $args));
    }

    public function querySelectorEval(mixed $selector, string|JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote('$eval', self::mergeNamedArguments(func_get_args(), $args));
    }

    #[Override]
    public function asElement(): ?ElementHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function asLocator(): Locator
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function backendNodeId(): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return array{height: int|float, width: int|float, x: int|float, y: int|float}|null
     */
    public function boundingBox(): ?array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return array{border: array{0: array{x: int|float, y: int|float}, 1: array{x: int|float, y: int|float}, 2: array{x: int|float, y: int|float}, 3: array{x: int|float, y: int|float}}, content: array{0: array{x: int|float, y: int|float}, 1: array{x: int|float, y: int|float}, 2: array{x: int|float, y: int|float}, 3: array{x: int|float, y: int|float}}, height: int|float, margin: array{0: array{x: int|float, y: int|float}, 1: array{x: int|float, y: int|float}, 2: array{x: int|float, y: int|float}, 3: array{x: int|float, y: int|float}}, padding: array{0: array{x: int|float, y: int|float}, 1: array{x: int|float, y: int|float}, 2: array{x: int|float, y: int|float}, 3: array{x: int|float, y: int|float}}, width: int|float}|null
     */
    public function boxModel(): ?array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{offset?: array{x: int|float, y: int|float}, debugHighlight?: bool, delay?: int|float, count?: int|float, button?: "left"|"right"|"middle"|"forward"|"back"})|null $options
     */
    public function click(?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{x: int|float, y: int|float})|null $offset
     *
     * @return array{x: int|float, y: int|float}
     */
    public function clickablePoint(?array $offset = null): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return Frame|Frame|null
     */
    public function contentFrame(): ?Frame
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    #[Override]
    public function dispose(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{x: int|float, y: int|float}|ElementHandle $target
     *
     * @return array{dragOperationsMask: int|float, files?: list<string>, items: list<array{baseURL?: string, data: string, mimeType: string, title?: string}>}|null
     */
    public function drag(array|ElementHandle $target): ?array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{delay: int|float})|null $options
     */
    public function dragAndDrop(ElementHandle $target, ?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{dragOperationsMask: int|float, files?: list<string>, items: list<array{baseURL?: string, data: string, mimeType: string, title?: string}>})|null $data
     */
    public function dragEnter(?array $data = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{dragOperationsMask: int|float, files?: list<string>, items: list<array{baseURL?: string, data: string, mimeType: string, title?: string}>})|null $data
     */
    public function dragOver(?array $data = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    #[Override]
    public function evaluate(string|JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }

    #[Override]
    public function evaluateHandle(string|JsFunction $pageFunction, mixed ...$args): JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }

    public function focus(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    public Frame $frame {
        get {
            return $this->getRemote('frame');
        }
    }

    #[Override]
    public function getProperty(string $propertyName): JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function hover(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function isHidden(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{threshold?: int|float})|null $options
     */
    public function isIntersectingViewport(?array $options = null): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function isVisible(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    #[Override]
    public function jsonValue(): mixed
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    #[Override]
    public function move(): ElementHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param "Q"|"d"|"r"|"x"|"y"|"a"|"b"|"i"|"p"|"q"|"s"|"u"|"g"|"0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"|"Accept"|"f"|"A"|"\\"|"/"|";"|":"|"C"|"L"|"O"|"Meta"|" "|"\n"|"\r"|">"|"~"|"+"|"c"|"e"|"h"|"l"|"n"|"o"|"t"|"v"|"w"|"\""|"'"|"*"|"j"|"k"|"m"|"z"|"D"|"R"|"X"|"Y"|"B"|"I"|"P"|"S"|"U"|"G"|"F"|"E"|"H"|"N"|"T"|"V"|"W"|"J"|"K"|"M"|"Z"|"-"|"_"|"Power"|"Eject"|"Abort"|"Help"|"Backspace"|"Tab"|"Numpad5"|"NumpadEnter"|"Enter"|"ShiftLeft"|"ShiftRight"|"ControlLeft"|"ControlRight"|"AltLeft"|"AltRight"|"Pause"|"CapsLock"|"Escape"|"Convert"|"NonConvert"|"Space"|"Numpad9"|"PageUp"|"Numpad3"|"PageDown"|"End"|"Numpad1"|"Home"|"Numpad7"|"ArrowLeft"|"Numpad4"|"Numpad8"|"ArrowUp"|"ArrowRight"|"Numpad6"|"Numpad2"|"ArrowDown"|"Select"|"Open"|"PrintScreen"|"Insert"|"Numpad0"|"Delete"|"NumpadDecimal"|"Digit0"|"Digit1"|"Digit2"|"Digit3"|"Digit4"|"Digit5"|"Digit6"|"Digit7"|"Digit8"|"Digit9"|"KeyA"|"KeyB"|"KeyC"|"KeyD"|"KeyE"|"KeyF"|"KeyG"|"KeyH"|"KeyI"|"KeyJ"|"KeyK"|"KeyL"|"KeyM"|"KeyN"|"KeyO"|"KeyP"|"KeyQ"|"KeyR"|"KeyS"|"KeyT"|"KeyU"|"KeyV"|"KeyW"|"KeyX"|"KeyY"|"KeyZ"|"MetaLeft"|"MetaRight"|"ContextMenu"|"NumpadMultiply"|"NumpadAdd"|"NumpadSubtract"|"NumpadDivide"|"F1"|"F2"|"F3"|"F4"|"F5"|"F6"|"F7"|"F8"|"F9"|"F10"|"F11"|"F12"|"F13"|"F14"|"F15"|"F16"|"F17"|"F18"|"F19"|"F20"|"F21"|"F22"|"F23"|"F24"|"NumLock"|"ScrollLock"|"AudioVolumeMute"|"AudioVolumeDown"|"AudioVolumeUp"|"MediaTrackNext"|"MediaTrackPrevious"|"MediaStop"|"MediaPlayPause"|"Semicolon"|"Equal"|"NumpadEqual"|"Comma"|"Minus"|"Period"|"Slash"|"Backquote"|"BracketLeft"|"Backslash"|"BracketRight"|"Quote"|"AltGraph"|"Props"|"Cancel"|"Clear"|"Shift"|"Control"|"Alt"|"ModeChange"|"Print"|"Execute"|"\u0000"|"="|","|"."|"`"|"["|"]"|"Attn"|"CrSel"|"ExSel"|"EraseEof"|"Play"|"ZoomOut"|")"|"!"|"@"|"#"|"$"|"%"|"^"|"&"|"("|"<"|"?"|"{"|"|"|"}"|"SoftLeft"|"SoftRight"|"Camera"|"Call"|"EndCall"|"VolumeDown"|"VolumeUp" $key
     * @param (array{text?: string, commands?: list<string>, delay?: int|float})|null                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         $options
     */
    public function press(string $key, ?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{optimizeForSpeed?: bool, type?: "webp"|"jpeg"|"png", quality?: int|float, fromSurface?: bool, fullPage?: bool, omitBackground?: bool, path?: string, clip?: array{height: int|float, scale?: int|float, width: int|float, x: int|float, y: int|float}, encoding?: "base64"|"binary", captureBeyondViewport?: bool})|null $options
     */
    public function screenshot(?array $options = null): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function scrollIntoView(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param string ...$values
     *
     * @return list<string>
     */
    public function select(mixed ...$values): array
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $values));
    }

    public function tap(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    #[Override]
    public function toString(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function touchEnd(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{delay?: int|float})|null $options
     */
    public function type(string $text, ?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param string ...$paths
     */
    public function uploadFile(mixed ...$paths): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $paths));
    }

    /**
     * @param (array{hidden?: bool, signal?: never, timeout?: int|float, visible?: bool})|null $options
     *
     * @return ElementHandle|null
     */
    public function waitForSelector(mixed $selector, ?array $options = null): mixed
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
