<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Nesk\Puphpeteer\RemoteObject;

class FileChooser extends RemoteObject
{
    /**
     * @param list<string> $paths
     */
    public function accept(array $paths): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function cancel(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function isMultiple(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
