<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Closure;
use Nesk\Puphpeteer\JsFunction;
use Nesk\Puphpeteer\RemoteObject;

class Frame extends RemoteObject
{
    /**
     * @return ElementHandle|null
     */
    public function querySelector(mixed $selector): mixed
    {
        return $this->invokeRemote('$', func_get_args());
    }

    /**
     * @param (array{isolate: bool})|null $options
     *
     * @return list<ElementHandle>
     */
    public function querySelectorAll(mixed $selector, ?array $options = null): mixed
    {
        return $this->invokeRemote('$$', func_get_args());
    }

    public function querySelectorAllEval(mixed $selector, string|JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote('$$eval', self::mergeNamedArguments(func_get_args(), $args));
    }

    public function querySelectorEval(mixed $selector, string|JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote('$eval', self::mergeNamedArguments(func_get_args(), $args));
    }

    /**
     * @param array{content?: string, id?: string, path?: string, type?: string, url?: string} $options
     */
    public function addScriptTag(array $options): ElementHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return list<Frame>
     */
    public function childFrames(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{offset?: array{x: int|float, y: int|float}, debugHighlight?: bool, delay?: int|float, count?: int|float, button?: "left"|"right"|"middle"|"back"|"forward"})|null $options
     */
    public function click(string $selector, ?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function content(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    public bool $detached {
        get {
            return $this->getRemote('detached');
        }
    }

    public function evaluate(string|JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }

    public function evaluateHandle(string|JsFunction $pageFunction, mixed ...$args): JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }

    public function focus(string $selector): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function frameElement(): ?ElementHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{referer?: string, referrerPolicy?: string, signal?: never, timeout?: int|float, waitUntil?: "load"|"domcontentloaded"|"networkidle0"|"networkidle2"|list<"load"|"domcontentloaded"|"networkidle0"|"networkidle2">})|null $options
     */
    public function goto(string $url, ?array $options = null): ?HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function hover(string $selector): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function isDetached(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function listenerCount(string $type): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function name(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (Closure|JsFunction)|null $handler
     */
    public function off(string $type, Closure|JsFunction|null $handler = null): Frame
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function on(string $type, Closure|JsFunction $handler): Frame
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function once(string $type, Closure|JsFunction $handler): Frame
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function page(): Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function parentFrame(): ?Frame
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (string)|null $type
     */
    public function removeAllListeners(?string $type = null): Frame
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param string ...$values
     *
     * @return list<string>
     */
    public function select(string $selector, mixed ...$values): array
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $values));
    }

    /**
     * @param (array{signal?: never, timeout?: int|float, waitUntil?: "load"|"domcontentloaded"|list<"load" | "domcontentloaded">})|null $options
     */
    public function setContent(string $html, ?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function tap(string $selector): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function title(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{delay?: int|float})|null $options
     */
    public function type(string $selector, string $text, ?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function url(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{signal?: never, timeout?: int|float, waitUntil?: "load"|"domcontentloaded"|"networkidle0"|"networkidle2"|list<"load"|"domcontentloaded"|"networkidle0"|"networkidle2">})|null $options
     */
    public function waitForNavigation(?array $options = null): ?HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{hidden?: bool, signal?: never, timeout?: int|float, visible?: bool})|null $options
     *
     * @return ElementHandle|null
     */
    public function waitForSelector(mixed $selector, ?array $options = null): mixed
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
