<?php

// @generated by bin/console generate. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Nesk\Puphpeteer\RemoteObject;

class HTTPResponse extends RemoteObject
{
    public function content(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function frame(): ?Frame
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function fromCache(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function fromServiceWorker(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return array<string, string>
     */
    public function headers(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function json(): mixed
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function ok(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return array{ip?: string, port?: int|float}
     */
    public function remoteAddress(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function request(): HTTPRequest
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function securityDetails(): ?SecurityDetails
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function status(): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function statusText(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function text(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return array{connectEnd: int|float, connectStart: int|float, dnsEnd: int|float, dnsStart: int|float, proxyEnd: int|float, proxyStart: int|float, pushEnd: int|float, pushStart: int|float, receiveHeadersEnd: int|float, receiveHeadersStart: int|float, requestTime: int|float, sendEnd: int|float, sendStart: int|float, sslEnd: int|float, sslStart: int|float, workerCacheLookupStart?: int|float, workerFetchStart: int|float, workerReady: int|float, workerRespondWithSettled: int|float, workerRouterEvaluationStart?: int|float, workerStart: int|float}|null
     */
    public function timing(): ?array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function url(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
