<?php

// @generated by bin/console generate. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Closure;
use Nesk\Puphpeteer\RemoteObject;

class HTTPRequest extends RemoteObject
{
    /**
     * @param ("failed"|"aborted"|"accessdenied"|"addressunreachable"|"blockedbyclient"|"blockedbyresponse"|"connectionaborted"|"connectionclosed"|"connectionfailed"|"connectionrefused"|"connectionreset"|"internetdisconnected"|"namenotresolved"|"timedout")|null $errorCode
     * @param (int|float)|null                                                                                                                                                                                                                                        $priority
     */
    public function abort(?string $errorCode = null, int|float|null $priority = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return "Failed"|"Aborted"|"TimedOut"|"AccessDenied"|"ConnectionClosed"|"ConnectionReset"|"ConnectionRefused"|"ConnectionAborted"|"ConnectionFailed"|"NameNotResolved"|"InternetDisconnected"|"AddressUnreachable"|"BlockedByClient"|"BlockedByResponse"|null
     */
    public function abortErrorReason(): ?string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    public CDPSession $client {
        get {
            return $this->getRemote('client');
        }
    }

    /**
     * @param (array{headers?: array<string, string>, method?: string, postData?: string, url?: string})|null $overrides
     * @param (int|float)|null                                                                                $priority
     */
    public function continue(?array $overrides = null, int|float|null $priority = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return array{headers?: array<string, string>, method?: string, postData?: string, url?: string}
     */
    public function continueRequestOverrides(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param Closure():mixed $pendingHandler
     */
    public function enqueueInterceptAction(Closure $pendingHandler): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return array{errorText: string}|null
     */
    public function failure(): ?array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function fetchPostData(): ?string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function finalizeInterceptions(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function frame(): ?Frame
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function hasPostData(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return array<string, string>
     */
    public function headers(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return array{action: "abort"|"respond"|"continue"|"disabled"|"none"|"already-handled", priority?: int|float}
     */
    public function interceptResolutionState(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function isInterceptResolutionHandled(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function isNavigationRequest(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function method(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function postData(): ?string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return list<HTTPRequest>
     */
    public function redirectChain(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return "media"|"other"|"font"|"script"|"image"|"document"|"manifest"|"fetch"|"ping"|"preflight"|"xhr"|"eventsource"|"prefetch"|"stylesheet"|"texttrack"|"websocket"|"signedexchange"|"cspviolationreport"|"fedcm"
     */
    public function resourceType(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{status?: int|float, headers?: array<string, mixed>, contentType?: string, body?: string} $response
     * @param (int|float)|null                                                                               $priority
     */
    public function respond(array $response, int|float|null $priority = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function response(): ?HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return array{status?: int|float, headers?: array<string, mixed>, contentType?: string, body?: string}|null
     */
    public function responseForRequest(): ?array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function url(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
