<?php

// @generated by bin/console generate. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Nesk\Puphpeteer\JsFunction;
use Nesk\Puphpeteer\RemoteObject;

class JSHandle extends RemoteObject
{
    public function asElement(): ?ElementHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function dispose(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function evaluate(string|JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }

    public function evaluateHandle(string|JsFunction $pageFunction, mixed ...$args): JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }

    public function getProperty(string $propertyName): JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function jsonValue(): mixed
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function move(): JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function toString(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
