<?php

// @generated by bin/console generate. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Closure;
use Nesk\Puphpeteer\JsFunction;
use Nesk\Puphpeteer\RemoteObject;

class Locator extends RemoteObject
{
    /**
     * @param (array{offset?: array{x: int|float, y: int|float}, debugHighlight?: bool, delay?: int|float, count?: int|float, button?: "left"|"right"|"middle"|"forward"|"back", signal?: never})|null $options
     */
    public function click(?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function clone(): Locator
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{typingThreshold?: int|float, signal?: never})|null $options
     */
    public function fill(string|bool $value, ?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function filter(JsFunction $predicate): Locator
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{signal?: never})|null $options
     */
    public function hover(?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function listenerCount(string $type): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function map(JsFunction $mapper): Locator
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (Closure|JsFunction)|null $handler
     */
    public function off(string $type, Closure|JsFunction|null $handler = null): Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function on(string $type, Closure|JsFunction $handler): Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function once(string $type, Closure|JsFunction $handler): Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (string)|null $type
     */
    public function removeAllListeners(?string $type = null): Locator
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{scrollTop?: int|float, scrollLeft?: int|float, signal?: never})|null $options
     */
    public function scroll(?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function setEnsureElementIsInTheViewport(bool $value): Locator
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function setTimeout(int|float $timeout): Locator
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param "hidden"|"visible"|null $visibility
     */
    public function setVisibility(?string $visibility): Locator
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function setWaitForEnabled(bool $value): Locator
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function setWaitForStableBoundingBox(bool $value): Locator
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    public int|float $timeout {
        get {
            return $this->getRemote('timeout');
        }
    }

    /**
     * @param (array{signal?: never})|null $options
     */
    public function wait(?array $options = null): mixed
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{signal?: never})|null $options
     */
    public function waitHandle(?array $options = null): JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param list<Locator> $locators
     */
    public function race(array $locators): Locator
    {
        return $this->invokeStaticRemote(__FUNCTION__, func_get_args());
    }
}
