<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Nesk\Puphpeteer\RemoteObject;

class Mouse extends RemoteObject
{
    /**
     * @param (array{delay?: int|float, count?: int|float, button?: "left"|"right"|"middle"|"forward"|"back"})|null $options
     */
    public function click(int|float $x, int|float $y, ?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{button?: "left"|"right"|"middle"|"forward"|"back"})|null $options
     */
    public function down(?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{x: int|float, y: int|float} $start
     * @param array{x: int|float, y: int|float} $target
     *
     * @return array{dragOperationsMask: int|float, files?: list<string>, items: list<array{baseURL?: string, data: string, mimeType: string, title?: string}>}
     */
    public function drag(array $start, array $target): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{x: int|float, y: int|float} $start
     * @param array{x: int|float, y: int|float} $target
     * @param (array{delay?: int|float})|null   $options
     */
    public function dragAndDrop(array $start, array $target, ?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{x: int|float, y: int|float}                                                                                                                $target
     * @param array{dragOperationsMask: int|float, files?: list<string>, items: list<array{baseURL?: string, data: string, mimeType: string, title?: string}>} $data
     */
    public function dragEnter(array $target, array $data): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{x: int|float, y: int|float}                                                                                                                $target
     * @param array{dragOperationsMask: int|float, files?: list<string>, items: list<array{baseURL?: string, data: string, mimeType: string, title?: string}>} $data
     */
    public function dragOver(array $target, array $data): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{x: int|float, y: int|float}                                                                                                                $target
     * @param array{dragOperationsMask: int|float, files?: list<string>, items: list<array{baseURL?: string, data: string, mimeType: string, title?: string}>} $data
     */
    public function drop(array $target, array $data): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{steps?: int|float})|null $options
     */
    public function move(int|float $x, int|float $y, ?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function reset(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{button?: "left"|"right"|"middle"|"forward"|"back"})|null $options
     */
    public function up(?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{deltaX?: int|float, deltaY?: int|float})|null $options
     */
    public function wheel(?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
