<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Amp\ByteStream\ReadableStream;
use Closure;
use Nesk\Puphpeteer\JsFunction;
use Nesk\Puphpeteer\RemoteObject;

class Page extends RemoteObject
{
    /**
     * @return ElementHandle|null
     */
    public function querySelector(mixed $selector): mixed
    {
        return $this->invokeRemote('$', func_get_args());
    }

    /**
     * @param (array{isolate: bool})|null $options
     *
     * @return list<ElementHandle>
     */
    public function querySelectorAll(mixed $selector, ?array $options = null): mixed
    {
        return $this->invokeRemote('$$', func_get_args());
    }

    public function querySelectorAllEval(mixed $selector, string|JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote('$$eval', self::mergeNamedArguments(func_get_args(), $args));
    }

    public function querySelectorEval(mixed $selector, string|JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote('$eval', self::mergeNamedArguments(func_get_args(), $args));
    }
    public Accessibility $accessibility {
        get {
            return $this->getRemote('accessibility');
        }
    }

    /**
     * @param array{content?: string, id?: string, path?: string, type?: string, url?: string} $options
     */
    public function addScriptTag(array $options): ElementHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{password: string, username: string}|null $credentials
     */
    public function authenticate(?array $credentials): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function bringToFront(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function browser(): Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function browserContext(): BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{path: string} $options
     */
    public function captureHeapSnapshot(array $options): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{offset?: array{x: int|float, y: int|float}, debugHighlight?: bool, delay?: int|float, count?: int|float, button?: "left"|"right"|"middle"|"back"|"forward"})|null $options
     */
    public function click(string $selector, ?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{runBeforeUnload?: bool})|null $options
     */
    public function close(?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function content(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param string ...$urls
     *
     * @return list<array{domain: string, expires: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, partitionKeyOpaque?: bool, path: string, priority?: "Low"|"Medium"|"High", sameSite?: "Strict"|"Lax"|"None"|"Default", secure: bool, session: bool, size: int|float, sourceScheme?: "Unset"|"NonSecure"|"Secure", value: string}>
     */
    public function cookies(mixed ...$urls): array
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $urls));
    }
    public Coverage $coverage {
        get {
            return $this->getRemote('coverage');
        }
    }

    public function createCDPSession(): CDPSession
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{displayHeaderFooter?: bool, footerTemplate?: string, format?: "letter"|"legal"|"tabloid"|"ledger"|"a0"|"a1"|"a2"|"a3"|"a4"|"a5"|"a6"|"LETTER"|"LEGAL"|"TABLOID"|"LEDGER"|"A0"|"A1"|"A2"|"A3"|"A4"|"A5"|"A6"|"Letter"|"Legal"|"Tabloid"|"Ledger", headerTemplate?: string, height?: string|int|float, landscape?: bool, margin?: array{bottom?: string|int|float, left?: string|int|float, right?: string|int|float, top?: string|int|float}, omitBackground?: bool, outline?: bool, pageRanges?: string, path?: string, preferCSSPageSize?: bool, printBackground?: bool, scale?: int|float, tagged?: bool, timeout?: int|float, waitForFonts?: bool, width?: string|int|float})|null $options
     */
    public function createPDFStream(?array $options = null): ReadableStream
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{domain?: string, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, path?: string, url?: string} ...$cookies
     */
    public function deleteCookie(mixed ...$cookies): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $cookies));
    }

    /**
     * @param array{userAgent: string, viewport: array{deviceScaleFactor?: int|float, hasTouch?: bool, height: int|float, isLandscape?: bool, isMobile?: bool, width: int|float}} $device
     */
    public function emulate(array $device): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function emulateCPUThrottling(int|float|null $factor): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function emulateFocusedPage(bool $enabled): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{isUserActive: bool, isScreenUnlocked: bool})|null $overrides
     */
    public function emulateIdleState(?array $overrides = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (string)|null $locale
     */
    public function emulateLocale(?string $locale = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (list<array{name: string, value: string}>)|null $features
     */
    public function emulateMediaFeatures(?array $features = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (string)|null $type
     */
    public function emulateMediaType(?string $type = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{download: int|float, latency: int|float, offline?: bool, upload: int|float}|null $networkConditions
     */
    public function emulateNetworkConditions(?array $networkConditions): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (string)|null $timezoneId
     */
    public function emulateTimezone(?string $timezoneId = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param ("none"|"blurredVision"|"reducedContrast"|"achromatopsia"|"deuteranopia"|"protanopia"|"tritanopia")|null $type
     */
    public function emulateVisionDeficiency(?string $type = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function evaluate(string|JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }

    public function evaluateHandle(string|JsFunction $pageFunction, mixed ...$args): JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }

    /**
     * @return array{identifier: string}
     */
    public function evaluateOnNewDocument(string|JsFunction $pageFunction, mixed ...$args): array
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }

    public function exposeFunction(string $name, Closure $pptrFunction): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function focus(string $selector): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return list<Frame>
     */
    public function frames(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function getDefaultNavigationTimeout(): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function getDefaultTimeout(): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{signal?: never, timeout?: int|float, waitUntil?: "load"|"domcontentloaded"|"networkidle0"|"networkidle2"|list<"load"|"domcontentloaded"|"networkidle0"|"networkidle2">})|null $options
     */
    public function goBack(?array $options = null): ?HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{signal?: never, timeout?: int|float, waitUntil?: "load"|"domcontentloaded"|"networkidle0"|"networkidle2"|list<"load"|"domcontentloaded"|"networkidle0"|"networkidle2">})|null $options
     */
    public function goForward(?array $options = null): ?HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{referer?: string, referrerPolicy?: string, signal?: never, timeout?: int|float, waitUntil?: "load"|"domcontentloaded"|"networkidle0"|"networkidle2"|list<"load"|"domcontentloaded"|"networkidle0"|"networkidle2">})|null $options
     */
    public function goto(string $url, ?array $options = null): ?HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function hasDevTools(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function hover(string $selector): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function isClosed(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function isDragInterceptionEnabled(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function isJavaScriptEnabled(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function isServiceWorkerBypassed(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    public Keyboard $keyboard {
        get {
            return $this->getRemote('keyboard');
        }
    }

    public function listenerCount(string $type): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function mainFrame(): Frame
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return array{Documents?: int|float, Frames?: int|float, JSEventListeners?: int|float, JSHeapTotalSize?: int|float, JSHeapUsedSize?: int|float, LayoutCount?: int|float, LayoutDuration?: int|float, Nodes?: int|float, RecalcStyleCount?: int|float, RecalcStyleDuration?: int|float, ScriptDuration?: int|float, TaskDuration?: int|float, Timestamp?: int|float}
     */
    public function metrics(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    public Mouse $mouse {
        get {
            return $this->getRemote('mouse');
        }
    }

    /**
     * @param (Closure|JsFunction)|null $handler
     */
    public function off(string $type, Closure|JsFunction|null $handler = null): Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function on(string $type, Closure|JsFunction $handler): Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function once(string $type, Closure|JsFunction $handler): Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function openDevTools(): Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{displayHeaderFooter?: bool, footerTemplate?: string, format?: "letter"|"legal"|"tabloid"|"ledger"|"a0"|"a1"|"a2"|"a3"|"a4"|"a5"|"a6"|"LETTER"|"LEGAL"|"TABLOID"|"LEDGER"|"A0"|"A1"|"A2"|"A3"|"A4"|"A5"|"A6"|"Letter"|"Legal"|"Tabloid"|"Ledger", headerTemplate?: string, height?: string|int|float, landscape?: bool, margin?: array{bottom?: string|int|float, left?: string|int|float, right?: string|int|float, top?: string|int|float}, omitBackground?: bool, outline?: bool, pageRanges?: string, path?: string, preferCSSPageSize?: bool, printBackground?: bool, scale?: int|float, tagged?: bool, timeout?: int|float, waitForFonts?: bool, width?: string|int|float})|null $options
     */
    public function pdf(?array $options = null): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function queryObjects(JSHandle $prototypeHandle): JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{ignoreCache?: bool, signal?: never, timeout?: int|float, waitUntil?: "load"|"domcontentloaded"|"networkidle0"|"networkidle2"|list<"load"|"domcontentloaded"|"networkidle0"|"networkidle2">})|null $options
     */
    public function reload(?array $options = null): ?HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (string)|null $type
     */
    public function removeAllListeners(?string $type = null): Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function removeExposedFunction(string $name): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function removeScriptToEvaluateOnNewDocument(string $identifier): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{contentWidth: int|float, contentHeight: int|float} $params
     */
    public function resize(array $params): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{optimizeForSpeed?: bool, type?: "png"|"jpeg"|"webp", quality?: int|float, fromSurface?: bool, fullPage?: bool, omitBackground?: bool, path?: string, clip?: array{height: int|float, scale?: int|float, width: int|float, x: int|float, y: int|float}, encoding?: "base64"|"binary", captureBeyondViewport?: bool})|null $options
     */
    public function screenshot(?array $options = null): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param string ...$values
     *
     * @return list<string>
     */
    public function select(string $selector, mixed ...$values): array
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $values));
    }

    public function setBypassCSP(bool $enabled): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function setBypassServiceWorker(bool $bypass): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (bool)|null $enabled
     */
    public function setCacheEnabled(?bool $enabled = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{signal?: never, timeout?: int|float, waitUntil?: "load"|"domcontentloaded"|list<"load" | "domcontentloaded">})|null $options
     */
    public function setContent(string $html, ?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{domain?: string, expires?: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, path?: string, priority?: "Low"|"Medium"|"High", sameSite?: "Strict"|"Lax"|"None"|"Default", secure?: bool, sourceScheme?: "Unset"|"NonSecure"|"Secure", url?: string, value: string} ...$cookies
     */
    public function setCookie(mixed ...$cookies): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $cookies));
    }

    public function setDefaultNavigationTimeout(int|float $timeout): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function setDefaultTimeout(int|float $timeout): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function setDragInterception(bool $enabled): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array<string, string> $headers
     */
    public function setExtraHTTPHeaders(array $headers): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{accuracy?: int|float, latitude: int|float, longitude: int|float} $options
     */
    public function setGeolocation(array $options): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function setJavaScriptEnabled(bool $enabled): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function setOfflineMode(bool $enabled): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function setRequestInterception(bool $value): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param array{deviceScaleFactor?: int|float, hasTouch?: bool, height: int|float, isLandscape?: bool, isMobile?: bool, width: int|float}|null $viewport
     */
    public function setViewport(?array $viewport): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function tap(string $selector): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function target(): Target
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function title(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    public Touchscreen $touchscreen {
        get {
            return $this->getRemote('touchscreen');
        }
    }
    public Tracing $tracing {
        get {
            return $this->getRemote('tracing');
        }
    }

    /**
     * @param (array{delay?: int|float})|null $options
     */
    public function type(string $selector, string $text, ?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function url(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return array{deviceScaleFactor?: int|float, hasTouch?: bool, height: int|float, isLandscape?: bool, isMobile?: bool, width: int|float}|null
     */
    public function viewport(): ?array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{signal?: never, timeout?: int|float})|null $options
     */
    public function waitForFileChooser(?array $options = null): FileChooser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param string|Closure(Frame):bool                        $urlOrPredicate
     * @param (array{signal?: never, timeout?: int|float})|null $options
     */
    public function waitForFrame(string|Closure $urlOrPredicate, ?array $options = null): Frame
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{signal?: never, timeout?: int|float, waitUntil?: "load"|"domcontentloaded"|"networkidle0"|"networkidle2"|list<"load"|"domcontentloaded"|"networkidle0"|"networkidle2">})|null $options
     */
    public function waitForNavigation(?array $options = null): ?HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{concurrency?: int|float, idleTime?: int|float, signal?: never, timeout?: int|float})|null $options
     */
    public function waitForNetworkIdle(?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param string|Closure(HTTPRequest):bool                  $urlOrPredicate
     * @param (array{signal?: never, timeout?: int|float})|null $options
     */
    public function waitForRequest(string|Closure $urlOrPredicate, ?array $options = null): HTTPRequest
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param string|Closure(HTTPResponse):bool                 $urlOrPredicate
     * @param (array{signal?: never, timeout?: int|float})|null $options
     */
    public function waitForResponse(string|Closure $urlOrPredicate, ?array $options = null): HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @param (array{hidden?: bool, signal?: never, timeout?: int|float, visible?: bool})|null $options
     *
     * @return ElementHandle|null
     */
    public function waitForSelector(mixed $selector, ?array $options = null): mixed
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function windowId(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return list<WebWorker>
     */
    public function workers(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
