<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Nesk\Puphpeteer\Internal\ScreenRecordingStream;

class ScreenRecording extends ScreenRecordingStream
{
    public function stop(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
