<?php

// @generated by bin/console generate. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Nesk\Puphpeteer\RemoteObject;

class SecurityDetails extends RemoteObject
{
    public function issuer(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function protocol(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return list<string>
     */
    public function subjectAlternativeNames(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function subjectName(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function validFrom(): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function validTo(): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
