<?php

// @generated by bin/console generate. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Nesk\Puphpeteer\RemoteObject;

class Target extends RemoteObject
{
    public function asPage(): Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function browser(): Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function browserContext(): BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function createCDPSession(): CDPSession
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function opener(): ?Target
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function page(): ?Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    /**
     * @return "page"|"background_page"|"service_worker"|"shared_worker"|"browser"|"webview"|"other"
     */
    public function type(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function url(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function worker(): ?WebWorker
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
