<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Nesk\Puphpeteer\RemoteObject;

class Touchscreen extends RemoteObject
{
    public function tap(int|float $x, int|float $y): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function touchEnd(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function touchMove(int|float $x, int|float $y): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
