<?php

// @generated by bin/console generate. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer\Puppeteer;

use Nesk\Puphpeteer\RemoteObject;

class Tracing extends RemoteObject
{
    /**
     * @param (array{bufferSize?: int|float, categories?: list<string>, path?: string, screenshots?: bool})|null $options
     */
    public function start(?array $options = null): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }

    public function stop(): ?string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
