<?php

declare(strict_types=1);

namespace Zoon\Puphpeteer\Tooling;

use PhpParser\Comment\Doc;
use PhpParser\Node;
use PhpParser\Node\Stmt;
use PhpParser\Parser;
use PhpParser\ParserFactory;
use PhpParser\PrettyPrinter\Standard;
use RuntimeException;

/**
 * Synchronizes declarations without loading client classes or executing their code.
 * Returned files are proposals: writing belongs to the updater.
 *
 * @psalm-type Parameter = array{name:string,type?:string,docType?:string,optional?:bool,default?:mixed,variadic?:bool}
 * @psalm-type Template = array{name:string,constraint?:string,default?:string}
 * @psalm-type Member = array{id:string,name:string,kind:string,jsName?:string,static?:bool,parameters?:list<Parameter>,returnType?:string,returnDocType?:string,type?:string,docType?:string,generatedDocLines?:list<string>,templates?:list<Template>}
 * @psalm-type ClassSpec = array{name:string,fqcn:string,file:string,extends?:string,members:list<Member>,generatedDocLines?:list<string>,templates?:list<Template>}
 * @psalm-type Diagnostic = array{code:string,componentId:string,symbolId:string,phpPath:string,phpLine:int,expected:mixed,actual:mixed}
 */
final class Synchronizer
{
    private const string HEADER = "<?php\n\n// @generated by tools/upstream/update.cjs. Do not edit.\n";
    private Parser $parser;
    private Standard $printer;
    /** @var list<Diagnostic> */
    private array $diagnostics = [];
    /** @var array<string,ClassSpec> */
    private array $classSpecs = [];

    public function __construct()
    {
        $this->parser = (new ParserFactory())->createForNewestSupportedVersion();
        $this->printer = new Standard();
    }

    /**
     * @param list<ClassSpec> $classes
     * @return array{diagnostics:list<Diagnostic>,files:list<array{path:string,content:string,changed:bool}>,deletedFiles:list<string>}
     */
    public function synchronize(string $root, array $classes): array
    {
        $this->diagnostics = [];
        $this->classSpecs = [];
        $root = realpath($root);
        if ($root === false) {
            throw new RuntimeException('Project root does not exist');
        }
        $destinations = [];
        foreach ($classes as $spec) {
            $this->classSpecs[strtolower(ltrim($spec['fqcn'], '\\'))] = $spec;
            foreach (['file:' . strtolower($spec['file']), 'class:' . strtolower($spec['fqcn'])] as $key) {
                if (isset($destinations[$key])) {
                    throw new RuntimeException('Duplicate generated destination: ' . $key);
                }
                $destinations[$key] = true;
            }
        }
        $files = [];
        $expectedPaths = [];
        foreach ($classes as $spec) {
            $path = $this->path($root, $spec['file']);
            $expectedPaths[$spec['file']] = true;
            $content = $this->classFile($spec);
            if ($this->lint($content, $spec)) {
                $files[] = ['path' => $spec['file'], 'content' => $content,
                    'changed' => !is_file($path) || file_get_contents($path) !== $content];
            }
        }
        $deletedFiles = [];
        if (is_dir($root . '/src')) {
            $iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($root . '/src', \FilesystemIterator::SKIP_DOTS));
            foreach ($iterator as $file) {
                if (!$file instanceof \SplFileInfo || !$file->isFile() || $file->getExtension() !== 'php') {
                    continue;
                }
                $relative = substr($file->getPathname(), strlen($root) + 1);
                $path = $this->path($root, $relative);
                if (!isset($expectedPaths[$relative]) && str_starts_with(file_get_contents($path) ?: '', self::HEADER)) {
                    $deletedFiles[] = $relative;
                }
            }
        }
        usort($files, static fn(array $a, array $b): int => $a['path'] <=> $b['path']);
        sort($deletedFiles);
        return ['diagnostics' => $this->diagnostics, 'files' => $files, 'deletedFiles' => $deletedFiles];
    }

    /**
     * @param ClassSpec $spec
     * @psalm-mutation-free
     */
    private function overrides(array $spec, string $method): bool
    {
        $parent = $spec['extends'] ?? '\\Nesk\\Puphpeteer\\RemoteObject';
        $visited = [];
        while (!isset($visited[strtolower($parent)])) {
            $visited[strtolower($parent)] = true;
            $parentSpec = $this->classSpecs[strtolower(ltrim($parent, '\\'))] ?? null;
            if ($parentSpec === null) {
                return false;
            }
            foreach ($parentSpec['members'] as $member) {
                if ($member['kind'] === 'method' && strcasecmp($member['name'], $method) === 0) {
                    return true;
                }
            }
            $parent = $parentSpec['extends'] ?? '\\Nesk\\Puphpeteer\\RemoteObject';
        }
        throw new RuntimeException('Cyclic generated inheritance');
    }

    /** @param ClassSpec $spec */
    private function classFile(array $spec): string
    {
        $parts = explode('\\', trim($spec['fqcn'], '\\'));
        $shortName = array_pop($parts);
        foreach (array_merge($parts, [$shortName]) as $part) {
            $this->identifier($part);
        }
        $namespace = implode('\\', $parts);
        $baseClass = $this->type($spec['extends'] ?? '\\Nesk\\Puphpeteer\\RemoteObject');
        $class = new Stmt\Class_($shortName, ['extends' => new Node\Name\FullyQualified(ltrim($baseClass, '\\'))]);
        $this->updateDoc($class, array_merge($this->templateLines($spec['templates'] ?? []), $spec['generatedDocLines'] ?? []));
        $names = [];
        foreach ($spec['members'] as $member) {
            $name = strtolower($member['name']);
            if (isset($names[$name])) {
                throw new RuntimeException('Duplicate generated method: ' . $name);
            }
            $names[$name] = true;
            try {
                $method = $this->declaration($member);
                if ($method instanceof Stmt\ClassMethod && $this->overrides($spec, $member['name'])) {
                    $method->attrGroups[] = new Node\AttributeGroup([new Node\Attribute(new Node\Name\FullyQualified('Override'))]);
                }
                $class->stmts[] = $method;
            } catch (UnrepresentableDeclaration $error) {
                $this->report('contract.unsupported', $member['id'], $spec['file'], 0, 'representable method', $error->getMessage());
            }
        }
        return self::HEADER . "\ndeclare(strict_types=1);\n\n" . ($namespace === '' ? '' : "namespace $namespace;\n\n")
            . $this->printer->prettyPrint([$class]) . "\n";
    }

    /** @param Member $member */
    private function declaration(array $member): Stmt\ClassMethod|Stmt\Property
    {
        $this->identifier($member['name']);
        if ($member['kind'] === 'property') {
            $name = $member['name'];
            $type = $this->type($member['type'] ?? 'mixed');
            $nodes = $this->parser->parse('<?php class GeneratedDeclaration { public ' . $type . ' $' . $name . ' { get { return $this->getRemote(' . var_export($name, true) . '); } } }');
            $property = $nodes[0]->stmts[0] ?? null;
            if (!$property instanceof Stmt\Property) { throw new RuntimeException('Invalid generated property'); }
            $this->updateDoc($property, $this->docLines($member));
            return $property;
        }
        if ($member['kind'] !== 'method' || ($member['static'] ?? false) || str_starts_with($member['name'], '__')) {
            throw new UnrepresentableDeclaration('Only public instance methods can use the remote bridge: ' . $member['id']);
        }
        $parameters = [];
        $variadic = null;
        foreach ($member['parameters'] ?? [] as $parameter) {
            $this->identifier($parameter['name']);
            if ($variadic !== null) {
                throw new UnrepresentableDeclaration('Variadic parameter must be last');
            }
            $isVariadic = $parameter['variadic'] ?? false;
            $text = $this->type($parameter['type'] ?? 'mixed') . ' ' . ($isVariadic ? '...' : '') . '$' . $parameter['name'];
            if (array_key_exists('default', $parameter) && !$isVariadic) {
                if (!$this->literal($parameter['default'])) {
                    throw new RuntimeException('Defaults must contain only JSON literals');
                }
                $text .= ' = ' . var_export($parameter['default'], true);
            } elseif (($parameter['optional'] ?? false) && !$isVariadic) {
                throw new UnrepresentableDeclaration('Optional parameter needs an explicit default: ' . $member['id'] . '.' . $parameter['name']);
            }
            $parameters[] = $text;
            if ($isVariadic) {
                $variadic = '$' . $parameter['name'];
            }
        }
        $args = 'func_get_args()';
        if ($variadic !== null) {
            $args = 'self::mergeNamedArguments(func_get_args(), ' . $variadic . ')';
        }
        $jsName = $member['jsName'] ?? $member['name'];
        $method = $jsName === $member['name'] ? '__FUNCTION__' : var_export($jsName, true);
        $returnType = $this->type($member['returnType'] ?? 'mixed');
        $body = ($returnType === 'void' ? '' : 'return ') . '$this->invokeRemote(' . $method . ', ' . $args . ');';
        $declaration = 'public function ' . $member['name'] . '(' . implode(', ', $parameters) . '): ' . $returnType . ' { ' . $body . ' }';
        $nodes = $this->parser->parse('<?php class GeneratedDeclaration { ' . $declaration . ' }');
        if ($nodes === null || !$nodes[0] instanceof Stmt\Class_) {
            throw new RuntimeException('Cannot construct declaration');
        }
        $node = $nodes[0]->stmts[0];
        if (!$node instanceof Stmt\ClassMethod) {
            throw new RuntimeException('Unexpected declaration');
        }
        $this->updateDoc($node, $this->docLines($member));
        return $node;
    }

    /**
     * @param Member $member
     * @return list<string>
     * @psalm-mutation-free
     */
    private function docLines(array $member): array
    {
        $lines = array_merge($this->templateLines($member['templates'] ?? []), $member['generatedDocLines'] ?? []);
        if ($member['kind'] === 'property') {
            $lines[] = '@var ' . ($member['docType'] ?? $member['type'] ?? 'mixed');
        } else {
            foreach ($member['parameters'] ?? [] as $parameter) {
                $lines[] = '@param ' . ($parameter['docType'] ?? $parameter['type'] ?? 'mixed') . ' ' . (($parameter['variadic'] ?? false) ? '...' : '') . '$' . $parameter['name'];
            }
            if ($member['name'] !== '__construct') {
                $lines[] = '@return ' . ($member['returnDocType'] ?? $member['returnType'] ?? 'mixed');
            }
        }
        foreach ($lines as $line) {
            if (str_contains($line, '*/') || str_contains($line, "\n") || str_contains($line, "\r")) {
                throw new RuntimeException('Generated annotations must be single safe lines');
            }
        }
        return $lines;
    }

    /**
     * @param list<Template> $templates
     * @return list<string>

     * @psalm-mutation-free
     */
    private function templateLines(array $templates): array
    {
        $lines = [];
        foreach ($templates as $template) {
            $this->identifier($template['name']);
            $line = '@template ' . $template['name'];
            if (isset($template['constraint'])) {
                $line .= ' as ' . $template['constraint'];
            }
            if (isset($template['default'])) {
                $line .= ' = ' . $template['default'];
            }
            if (str_contains($line, '*/') || str_contains($line, "\n") || str_contains($line, "\r")) {
                throw new RuntimeException('Unsafe template annotation');
            }
            $lines[] = $line;
        }
        return $lines;
    }

    /** @param list<string> $lines */
    private function updateDoc(Node $node, array $lines): void
    {
        if ($lines === []) {
            return;
        }
        foreach ($lines as $line) {
            if (str_contains($line, '*/') || str_contains($line, "\n") || str_contains($line, "\r")) {
                throw new RuntimeException('Unsafe generated documentation');
            }
        }
        $node->setDocComment(new Doc("/**\n * " . implode("\n * ", $lines) . "\n */"));
    }

    /** @psalm-pure */
    private function identifier(string $name): void
    {
        if (!preg_match('/^[a-zA-Z_][a-zA-Z0-9_]*$/D', $name)) {
            throw new RuntimeException('Invalid PHP identifier: ' . $name);
        }
    }

    /** @psalm-pure */
    private function type(string $type): string
    {
        if (!preg_match('/^[?(\\\\a-zA-Z_][\\\\a-zA-Z0-9_|&?()]*$/D', $type)) {
            throw new RuntimeException('Invalid PHP type: ' . $type);
        }
        return $type;
    }

    /** @psalm-mutation-free */
    private function literal(mixed $value): bool
    {
        if (is_array($value)) {
            foreach ($value as $item) {
                if (!$this->literal($item)) {
                    return false;
                }
            }
            return true;
        }
        return $value === null || is_scalar($value);
    }

    private function path(string $root, string $relative): string
    {
        if ($relative === '' || str_starts_with($relative, '/') || str_contains($relative, '\\') || in_array('..', explode('/', $relative), true)) {
            throw new RuntimeException('Expected a safe relative PHP path');
        }
        $root = realpath($root);
        if ($root === false) {
            throw new RuntimeException('Project root does not exist');
        }
        $path = $root . '/' . $relative;
        $ancestor = $path;
        while (!file_exists($ancestor) && !is_link($ancestor)) {
            $ancestor = dirname($ancestor);
        }
        $resolved = realpath($ancestor);
        if ($resolved === false || ($resolved !== $root && !str_starts_with($resolved, $root . '/'))) {
            throw new RuntimeException('Mapped file escapes the project root');
        }
        return $path;
    }

    /** @param ClassSpec $spec */
    private function lint(string $content, array $spec): bool
    {
        $path = tempnam(sys_get_temp_dir(), 'puphpeteer-lint-');
        if ($path === false) {
            throw new RuntimeException('Cannot create PHP lint staging file');
        }
        try {
            if (file_put_contents($path, $content) === false) {
                throw new RuntimeException('Cannot write PHP lint staging file');
            }
            $process = proc_open([PHP_BINARY, '-l', $path], [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['redirect', 1]], $pipes);
            if (!is_resource($process)) {
                throw new RuntimeException('Cannot start PHP syntax checker');
            }
            fclose($pipes[0]);
            $output = stream_get_contents($pipes[1]);
            fclose($pipes[1]);
            $code = proc_close($process);
            if ($code !== 0) {
                $this->report('contract.conflict', $spec['name'], $spec['file'], 0, 'PHP syntax accepted by php -l', str_replace($path, $spec['file'], trim($output === false ? '' : $output)));
                return false;
            }
            return true;
        } finally {
            unlink($path);
        }
    }

    /** @psalm-external-mutation-free */
    private function report(string $code, string $id, string $path, int $line, mixed $expected, mixed $actual): void
    {
        $this->diagnostics[] = ['code' => $code, 'componentId' => 'PhpSynchronizer', 'symbolId' => $id, 'phpPath' => $path, 'phpLine' => max(0, $line), 'expected' => $expected, 'actual' => $actual];
    }
}
