#!/usr/bin/env node
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const {spawnSync} = require('node:child_process');
const {extractPublicApi} = require('./public-api.cjs');
const {resolveSources} = require('./source-resolver.cjs');
const {buildPhpModel} = require('./php-model.cjs');
const {generateAliases} = require('./aliases.cjs');
const {generateReadmeBadges} = require('./readme-badges.cjs');
const {readJson,json,inside,sortDiagnostics,validateConfig} = require('./model.cjs');
const toolRoot = path.resolve(__dirname,'../..');
function applyGeneratedFiles(root, files, deletedFiles, check=false) {
 const changedFiles=[];
 for(const file of files){const dest=inside(root,file.path);if(fs.existsSync(dest)&&fs.readFileSync(dest,'utf8')===file.content)continue;changedFiles.push(file.path);if(!check){fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,file.content);}}
 for(const relative of deletedFiles){const dest=inside(root,relative);if(!fs.existsSync(dest))continue;changedFiles.push(relative);if(!check)fs.unlinkSync(dest);}
 return changedFiles;
}
async function updatePhp(root=toolRoot,{check=false,offline=false,modelOnly=false,onProgress=()=>{}}={}) {
 let diagnostics = [];
 try {
 onProgress(1, 'Checking dependencies');
 const config = validateConfig(readJson(path.join(root,'upstream/config.json')));
 const source=await resolveSources({root,offline});
 onProgress(2, 'Parsing TypeScript');
 const api=extractPublicApi(source.entry,{root});
 onProgress(3, 'Building the PHP model');
 const model=buildPhpModel({api,config});
 diagnostics=sortDiagnostics([...api.diagnostics,...model.diagnostics]);
 let files=[{path:'upstream/lock.json',content:json(source.lock)}];
 files.push(...generateReadmeBadges(root, source.lock));
 let deletedFiles=[];
 onProgress(4, modelOnly ? 'Skipping PHP generation: model-only' : 'Generating PHP and checking syntax');
 if(!modelOnly){
  const result=spawnSync('php',[path.join(toolRoot,'tools/php/synchronize.php')],{cwd:root,input:json({root,classes:model.classes}),encoding:'utf8',maxBuffer:32*1024*1024});
  if(result.error || ![0,1].includes(result.status))throw new Error(`PHP emitter failed: ${result.stderr || result.error || result.stdout}`);
  const sync=JSON.parse(result.stdout);
  if(sync.diagnostics?.length)throw Object.assign(new Error(`PHP emitter diagnostics: ${json(sync.diagnostics)}`), {errors:sync.diagnostics.length});
  files.push(...sync.files, generateAliases(model.classes));
  deletedFiles=sync.deletedFiles;
  const entries=model.classes.map(c=>`        '${c.name}' => \\${c.fqcn}::class,`).join('\n');
  files.push({path:'src/Internal/GeneratedRegistry.php',content:`<?php\ndeclare(strict_types=1);\nnamespace Nesk\\Puphpeteer\\Internal;\n\n/**\n * @internal Generated by tools/upstream/update.cjs.\n * @psalm-immutable\n */\nfinal class GeneratedRegistry\n{\n    /** @var array<string, class-string<\\Nesk\\Puphpeteer\\RemoteObject>> */\n    public const CLASSES = [\n${entries}\n    ];\n}\n`});
 }
 onProgress(5, 'Formatting PHP');
 const formatted=spawnSync('php',[path.join(toolRoot,'tools/php/format.php')],{cwd:root,input:json(files),encoding:'utf8',maxBuffer:32*1024*1024});
 if(formatted.error || formatted.status!==0)throw new Error(`PHP formatting failed: ${formatted.stderr || formatted.error}`);
 files=JSON.parse(formatted.stdout);
 const outputPaths=new Set(files.map(file=>file.path));
 deletedFiles=deletedFiles.filter(file=>!outputPaths.has(file));
 onProgress(6, check ? 'Checking files' : 'Writing files');
 const changedFiles=applyGeneratedFiles(root,files,deletedFiles,check);
 return {changedFiles,deletedFiles,diagnostics,errors:check&&changedFiles.length?1:0,warnings:diagnostics.length,classes:model.classes.length,generated:model.coverage.filter(m=>m.status==='generated').length,total:model.coverage.length,exitCode:check&&changedFiles.length?1:0};
 } catch (error) {
  error.warnings = diagnostics.length;
  throw error;
 }
}
async function runCli(root=toolRoot,args=process.argv.slice(2)) {
 try {
  if(args.some(a=>!['--check','--offline','--model-only','--verbose','--progress'].includes(a)))throw new Error('Usage: update.cjs [--check] [--offline] [--model-only] [--verbose] [--progress]');
  const result=await updatePhp(root,{check:args.includes('--check'),offline:args.includes('--offline'),modelOnly:args.includes('--model-only'),onProgress:args.includes('--progress') ? (step,message)=>process.stdout.write('@progress '+JSON.stringify({step,total:6,message})+'\n') : undefined});
  if (!args.includes('--verbose')) result.diagnostics = [];
  process.stdout.write(json(result));
  process.exitCode=result.exitCode;
 } catch(error) {
  process.stdout.write(json({errors:error.errors ?? 1,warnings:error.warnings ?? 0,diagnostics:[],exitCode:2}));
  process.stderr.write(`${error.stack}\n`);
  process.exitCode=2;
 }
}
if(require.main===module)runCli();
module.exports={updatePhp,applyGeneratedFiles,runCli};
