#!/usr/bin/env node
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const {spawnSync} = require('node:child_process');
const {extractPublicApi} = require('./public-api.cjs');
const {resolveSources} = require('./source-resolver.cjs');
const {buildPhpModel} = require('./php-model.cjs');
const {generateAliases} = require('./aliases.cjs');
const {readJson,json,inside,sortDiagnostics,validateConfig} = require('./model.cjs');
const toolRoot = path.resolve(__dirname,'../..');
function applyGeneratedFiles(root, files, deletedFiles, check=false) {
 const changedFiles=[];
 for(const file of files){const dest=inside(root,file.path);if(fs.existsSync(dest)&&fs.readFileSync(dest,'utf8')===file.content)continue;changedFiles.push(file.path);if(!check){fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,file.content);}}
 for(const relative of deletedFiles){const dest=inside(root,relative);if(!fs.existsSync(dest))continue;changedFiles.push(relative);if(!check)fs.unlinkSync(dest);}
 return changedFiles;
}
async function updatePhp(root=toolRoot,{check=false,offline=false,modelOnly=false}={}) {
 const config = validateConfig(readJson(path.join(root,'upstream/config.json')));
 const source=await resolveSources({root,offline});
 const api=extractPublicApi(source.entry,{root});
 const model=buildPhpModel({api,config});
 const files=[{path:'upstream/api.json',content:json(api)},{path:'upstream/lock.json',content:json(source.lock)},
 {path:'upstream/coverage.json',content:json({schemaVersion:1,note:'Declaration coverage only; does not imply runtime or test coverage.', total:model.coverage.length,generated:model.coverage.filter(m=>m.status==='generated').length,members:model.coverage,diagnostics:sortDiagnostics([...api.diagnostics,...model.diagnostics])})}];
 let deletedFiles=[];
 if(!modelOnly){
  const result=spawnSync('php',[path.join(toolRoot,'tools/php/synchronize.php')],{cwd:root,input:json({root,classes:model.classes}),encoding:'utf8',maxBuffer:32*1024*1024});
  if(result.error || ![0,1].includes(result.status))throw new Error(`PHP emitter failed: ${result.stderr || result.error || result.stdout}`);
  const sync=JSON.parse(result.stdout);
  if(sync.diagnostics?.length)throw new Error(`PHP emitter diagnostics: ${json(sync.diagnostics)}`);
  files.push(...sync.files, generateAliases(model.classes));
  deletedFiles=sync.deletedFiles;
  const entries=model.classes.map(c=>`        '${c.name}' => \\${c.fqcn}::class,`).join('\n');
  files.push({path:'src/Internal/GeneratedRegistry.php',content:`<?php\ndeclare(strict_types=1);\nnamespace Nesk\\Puphpeteer\\Internal;\n\n/**\n * @internal Generated by tools/upstream/update.cjs.\n * @psalm-immutable\n */\nfinal class GeneratedRegistry\n{\n    /** @var array<string, class-string<\\Nesk\\Puphpeteer\\RemoteObject>> */\n    public const CLASSES = [\n${entries}\n    ];\n}\n`});
 }
 const outputPaths=new Set(files.map(file=>file.path));
 deletedFiles=deletedFiles.filter(file=>!outputPaths.has(file));
 const changedFiles=applyGeneratedFiles(root,files,deletedFiles,check);
 return {changedFiles,deletedFiles,classes:model.classes.length,generated:model.coverage.filter(m=>m.status==='generated').length,total:model.coverage.length,exitCode:check&&changedFiles.length?1:0};
}
if(require.main===module){const args=process.argv.slice(2);if(args.some(a=>!['--check','--offline','--model-only'].includes(a)))throw new Error('Usage: update.cjs [--check] [--offline] [--model-only]');updatePhp(toolRoot,{check:args.includes('--check'),offline:args.includes('--offline'),modelOnly:args.includes('--model-only')}).then(r=>{process.stdout.write(json(r));process.exitCode=r.exitCode;}).catch(e=>{process.stderr.write(`${e.stack}\n`);process.exitCode=2;});}
module.exports={updatePhp,applyGeneratedFiles};
