<?php
declare(strict_types=1);
namespace Nesk\Puphpeteer\Internal;

/**
 * @internal Generated by tools/upstream/update.cjs.
 * @psalm-immutable
 */
final class GeneratedRegistry
{
    /** @var array<string, class-string<\Nesk\Puphpeteer\RemoteObject>> */
    public const CLASSES = [
        'Accessibility' => \Nesk\Puphpeteer\Puppeteer\Accessibility::class,
        'Browser' => \Nesk\Puphpeteer\Puppeteer\Browser::class,
        'BrowserContext' => \Nesk\Puphpeteer\Puppeteer\BrowserContext::class,
        'CDPSession' => \Nesk\Puphpeteer\Puppeteer\CDPSession::class,
        'ConsoleMessage' => \Nesk\Puphpeteer\Puppeteer\ConsoleMessage::class,
        'Coverage' => \Nesk\Puphpeteer\Puppeteer\Coverage::class,
        'Dialog' => \Nesk\Puphpeteer\Puppeteer\Dialog::class,
        'ElementHandle' => \Nesk\Puphpeteer\Puppeteer\ElementHandle::class,
        'FileChooser' => \Nesk\Puphpeteer\Puppeteer\FileChooser::class,
        'Frame' => \Nesk\Puphpeteer\Puppeteer\Frame::class,
        'HTTPRequest' => \Nesk\Puphpeteer\Puppeteer\HTTPRequest::class,
        'HTTPResponse' => \Nesk\Puphpeteer\Puppeteer\HTTPResponse::class,
        'JSHandle' => \Nesk\Puphpeteer\Puppeteer\JSHandle::class,
        'Keyboard' => \Nesk\Puphpeteer\Puppeteer\Keyboard::class,
        'Mouse' => \Nesk\Puphpeteer\Puppeteer\Mouse::class,
        'Page' => \Nesk\Puphpeteer\Puppeteer\Page::class,
        'SecurityDetails' => \Nesk\Puphpeteer\Puppeteer\SecurityDetails::class,
        'Target' => \Nesk\Puphpeteer\Puppeteer\Target::class,
        'Touchscreen' => \Nesk\Puphpeteer\Puppeteer\Touchscreen::class,
        'Tracing' => \Nesk\Puphpeteer\Puppeteer\Tracing::class,
        'WebWorker' => \Nesk\Puphpeteer\Puppeteer\WebWorker::class,
    ];
}
