<?php
declare(strict_types=1);
namespace Nesk\Puphpeteer\Internal;

/**
 * @internal Generated by tools/upstream/update.cjs.
 * @psalm-immutable
 */
final class GeneratedRegistry
{
    /** @var array<string, class-string<\Nesk\Puphpeteer\RemoteObject>> */
    public const CLASSES = [
        'Accessibility' => \Nesk\Puphpeteer\Accessibility::class,
        'Browser' => \Nesk\Puphpeteer\Browser::class,
        'BrowserContext' => \Nesk\Puphpeteer\BrowserContext::class,
        'CDPSession' => \Nesk\Puphpeteer\CDPSession::class,
        'ConsoleMessage' => \Nesk\Puphpeteer\ConsoleMessage::class,
        'Coverage' => \Nesk\Puphpeteer\Coverage::class,
        'Dialog' => \Nesk\Puphpeteer\Dialog::class,
        'ElementHandle' => \Nesk\Puphpeteer\ElementHandle::class,
        'FileChooser' => \Nesk\Puphpeteer\FileChooser::class,
        'Frame' => \Nesk\Puphpeteer\Frame::class,
        'HTTPRequest' => \Nesk\Puphpeteer\HTTPRequest::class,
        'HTTPResponse' => \Nesk\Puphpeteer\HTTPResponse::class,
        'JSHandle' => \Nesk\Puphpeteer\JSHandle::class,
        'Keyboard' => \Nesk\Puphpeteer\Keyboard::class,
        'Mouse' => \Nesk\Puphpeteer\Mouse::class,
        'Page' => \Nesk\Puphpeteer\Page::class,
        'SecurityDetails' => \Nesk\Puphpeteer\SecurityDetails::class,
        'Target' => \Nesk\Puphpeteer\Target::class,
        'Touchscreen' => \Nesk\Puphpeteer\Touchscreen::class,
        'Tracing' => \Nesk\Puphpeteer\Tracing::class,
        'WebWorker' => \Nesk\Puphpeteer\WebWorker::class,
    ];
}
