<?php

declare(strict_types=1);

namespace Nesk\Puphpeteer\Internal;

use Nesk\Puphpeteer\Puppeteer\Accessibility;
use Nesk\Puphpeteer\Puppeteer\Browser;
use Nesk\Puphpeteer\Puppeteer\BrowserContext;
use Nesk\Puphpeteer\Puppeteer\CDPSession;
use Nesk\Puphpeteer\Puppeteer\Connection;
use Nesk\Puphpeteer\Puppeteer\ConsoleMessage;
use Nesk\Puphpeteer\Puppeteer\Coverage;
use Nesk\Puphpeteer\Puppeteer\Dialog;
use Nesk\Puphpeteer\Puppeteer\ElementHandle;
use Nesk\Puphpeteer\Puppeteer\FileChooser;
use Nesk\Puphpeteer\Puppeteer\Frame;
use Nesk\Puphpeteer\Puppeteer\HTTPRequest;
use Nesk\Puphpeteer\Puppeteer\HTTPResponse;
use Nesk\Puphpeteer\Puppeteer\JSHandle;
use Nesk\Puphpeteer\Puppeteer\Keyboard;
use Nesk\Puphpeteer\Puppeteer\Locator;
use Nesk\Puphpeteer\Puppeteer\Mouse;
use Nesk\Puphpeteer\Puppeteer\Page;
use Nesk\Puphpeteer\Puppeteer\ScreenRecording;
use Nesk\Puphpeteer\Puppeteer\SecurityDetails;
use Nesk\Puphpeteer\Puppeteer\Target;
use Nesk\Puphpeteer\Puppeteer\Touchscreen;
use Nesk\Puphpeteer\Puppeteer\Tracing;
use Nesk\Puphpeteer\Puppeteer\WebWorker;
use Nesk\Puphpeteer\RemoteObject;

/**
 * @internal generated by bin/console generate
 *
 * @psalm-immutable
 */
final class GeneratedRegistry
{
    /** @var array<string, class-string<RemoteObject>> */
    public const CLASSES = [
        'Accessibility' => Accessibility::class,
        'Browser' => Browser::class,
        'BrowserContext' => BrowserContext::class,
        'CDPSession' => CDPSession::class,
        'Connection' => Connection::class,
        'ConsoleMessage' => ConsoleMessage::class,
        'Coverage' => Coverage::class,
        'Dialog' => Dialog::class,
        'ElementHandle' => ElementHandle::class,
        'FileChooser' => FileChooser::class,
        'Frame' => Frame::class,
        'HTTPRequest' => HTTPRequest::class,
        'HTTPResponse' => HTTPResponse::class,
        'JSHandle' => JSHandle::class,
        'Keyboard' => Keyboard::class,
        'Locator' => Locator::class,
        'Mouse' => Mouse::class,
        'Page' => Page::class,
        'ScreenRecording' => ScreenRecording::class,
        'SecurityDetails' => SecurityDetails::class,
        'Target' => Target::class,
        'Touchscreen' => Touchscreen::class,
        'Tracing' => Tracing::class,
        'WebWorker' => WebWorker::class,
    ];
}
