<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class BrowserContext extends \Nesk\Puphpeteer\RemoteObject
{
    /**
     * @return \Nesk\Puphpeteer\Browser
     */
    public function browser(): \Nesk\Puphpeteer\Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return void
     */
    public function clearPermissionOverrides(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return void
     */
    public function close(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @var bool
     */
    public bool $closed {
        get {
            return $this->getRemote('closed');
        }
    }
    /**
     * @return list<array{domain: string, expires: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, partitionKeyOpaque?: bool, path: string, priority?: "Low"|"Medium"|"High", sameSite?: "Strict"|"Lax"|"None"|"Default", secure: bool, session: bool, size: int|float, sourceScheme?: "Unset"|"NonSecure"|"Secure", value: string}>
     */
    public function cookies(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param array{domain: string, expires: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, partitionKeyOpaque?: bool, path: string, priority?: "Low"|"Medium"|"High", sameSite?: "Strict"|"Lax"|"None"|"Default", secure: bool, session: bool, size: int|float, sourceScheme?: "Unset"|"NonSecure"|"Secure", value: string} ...$cookies
     * @return void
     */
    public function deleteCookie(mixed ...$cookies): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $cookies));
    }
    /**
     * @param array{domain?: string, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, path?: string, url?: string} ...$filters
     * @return void
     */
    public function deleteMatchingCookies(mixed ...$filters): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $filters));
    }
    /**
     * @var null|string
     */
    public null|string $id {
        get {
            return $this->getRemote('id');
        }
    }
    /**
     * @param string $type
     * @return int|float
     */
    public function listenerCount(string $type): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{type?: "tab", background?: bool}|array{type: "window", windowBounds?: array{height?: int|float, left?: int|float, top?: int|float, width?: int|float, windowState?: "normal"|"minimized"|"maximized"|"fullscreen"}, background?: bool})|null $options
     * @return \Nesk\Puphpeteer\Page
     */
    public function newPage(array|null $options = NULL): \Nesk\Puphpeteer\Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @param (\Closure|\Nesk\Puphpeteer\JsFunction)|null $handler
     * @return \Nesk\Puphpeteer\BrowserContext
     */
    public function off(string $type, \Closure|\Nesk\Puphpeteer\JsFunction|null $handler = NULL): \Nesk\Puphpeteer\BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @param \Closure|\Nesk\Puphpeteer\JsFunction $handler
     * @return \Nesk\Puphpeteer\BrowserContext
     */
    public function on(string $type, \Closure|\Nesk\Puphpeteer\JsFunction $handler): \Nesk\Puphpeteer\BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @param \Closure|\Nesk\Puphpeteer\JsFunction $handler
     * @return \Nesk\Puphpeteer\BrowserContext
     */
    public function once(string $type, \Closure|\Nesk\Puphpeteer\JsFunction $handler): \Nesk\Puphpeteer\BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $origin
     * @param list<"accelerometer"|"ambient-light-sensor"|"background-sync"|"camera"|"clipboard-read"|"clipboard-sanitized-write"|"clipboard-write"|"geolocation"|"gyroscope"|"idle-detection"|"keyboard-lock"|"magnetometer"|"microphone"|"midi-sysex"|"midi"|"notifications"|"payment-handler"|"persistent-storage"|"pointer-lock"> $permissions
     * @return void
     */
    public function overridePermissions(string $origin, array $permissions): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (bool)|null $includeAll
     * @return list<\Nesk\Puphpeteer\Page>
     */
    public function pages(bool|null $includeAll = NULL): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (string)|null $type
     * @return \Nesk\Puphpeteer\BrowserContext
     */
    public function removeAllListeners(string|null $type = NULL): \Nesk\Puphpeteer\BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param array{domain: string, expires?: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, path?: string, priority?: "Low"|"Medium"|"High", sameSite?: "Strict"|"Lax"|"None"|"Default", secure?: bool, sourceScheme?: "Unset"|"NonSecure"|"Secure", value: string} ...$cookies
     * @return void
     */
    public function setCookie(mixed ...$cookies): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $cookies));
    }
    /**
     * @param string $origin
     * @param array{permission: array{allowWithoutSanitization?: bool, name: string, panTiltZoom?: bool, sysex?: bool, userVisibleOnly?: bool}, state: "granted"|"denied"|"prompt"} ...$permissions
     * @return void
     */
    public function setPermission(string $origin, mixed ...$permissions): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $permissions));
    }
    /**
     * @return list<\Nesk\Puphpeteer\Target>
     */
    public function targets(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param \Closure(\Nesk\Puphpeteer\Target):bool $predicate
     * @param (array{signal?: never, timeout?: int|float})|null $options
     * @return \Nesk\Puphpeteer\Target
     */
    public function waitForTarget(\Closure $predicate, array|null $options = NULL): \Nesk\Puphpeteer\Target
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
