<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class Browser extends \Nesk\Puphpeteer\RemoteObject
{
    /**
     * @param array{colorDepth?: int|float, devicePixelRatio?: int|float, height: int|float, isInternal?: bool, label?: string, left: int|float, rotation?: int|float, top: int|float, width: int|float, workAreaInsets?: array{bottom?: int|float, left?: int|float, right?: int|float, top?: int|float}} $params
     * @return array{availHeight: int|float, availLeft: int|float, availTop: int|float, availWidth: int|float, colorDepth: int|float, devicePixelRatio: int|float, height: int|float, id: string, isExtended: bool, isInternal: bool, isPrimary: bool, label: string, left: int|float, orientation: array{angle: int|float, type: string}, top: int|float, width: int|float}
     */
    public function addScreen(array $params): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return list<\Nesk\Puphpeteer\BrowserContext>
     */
    public function browserContexts(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return void
     */
    public function close(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @var bool
     */
    public bool $connected {
        get {
            return $this->getRemote('connected');
        }
    }
    /**
     * @return list<array{domain: string, expires: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, partitionKeyOpaque?: bool, path: string, priority?: "Low"|"Medium"|"High", sameParty?: bool, sameSite?: "Strict"|"Lax"|"None", secure: bool, session: bool, size: int|float, sourceScheme?: "Unset"|"NonSecure"|"Secure", value: string}>
     */
    public function cookies(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{downloadBehavior?: array{downloadPath?: string, policy: "deny"|"allow"|"allowAndName"|"default"}, proxyBypassList?: list<string>, proxyServer?: string})|null $options
     * @return \Nesk\Puphpeteer\BrowserContext
     */
    public function createBrowserContext(array|null $options = NULL): \Nesk\Puphpeteer\BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return \Nesk\Puphpeteer\BrowserContext
     */
    public function defaultBrowserContext(): \Nesk\Puphpeteer\BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param array{domain: string, expires: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, partitionKeyOpaque?: bool, path: string, priority?: "Low"|"Medium"|"High", sameParty?: bool, sameSite?: "Strict"|"Lax"|"None", secure: bool, session: bool, size: int|float, sourceScheme?: "Unset"|"NonSecure"|"Secure", value: string} ...$cookies
     * @return void
     */
    public function deleteCookie(mixed ...$cookies): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $cookies));
    }
    /**
     * @param array{domain?: string, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, path?: string, url?: string} ...$filters
     * @return void
     */
    public function deleteMatchingCookies(mixed ...$filters): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $filters));
    }
    /**
     * @return void
     */
    public function disconnect(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $windowId
     * @return array{height?: int|float, left?: int|float, top?: int|float, width?: int|float, windowState?: "normal"|"minimized"|"maximized"|"fullscreen"}
     */
    public function getWindowBounds(string $windowId): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $path
     * @return string
     */
    public function installExtension(string $path): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return bool
     */
    public function isConnected(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @return int|float
     */
    public function listenerCount(string $type): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{type?: "tab", background?: bool}|array{type: "window", windowBounds?: array{height?: int|float, left?: int|float, top?: int|float, width?: int|float, windowState?: "normal"|"minimized"|"maximized"|"fullscreen"}, background?: bool})|null $options
     * @return \Nesk\Puphpeteer\Page
     */
    public function newPage(array|null $options = NULL): \Nesk\Puphpeteer\Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @param (\Closure|\Nesk\Puphpeteer\JsFunction)|null $handler
     * @return \Nesk\Puphpeteer\Browser
     */
    public function off(string $type, \Closure|\Nesk\Puphpeteer\JsFunction|null $handler = NULL): \Nesk\Puphpeteer\Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @param \Closure|\Nesk\Puphpeteer\JsFunction $handler
     * @return \Nesk\Puphpeteer\Browser
     */
    public function on(string $type, \Closure|\Nesk\Puphpeteer\JsFunction $handler): \Nesk\Puphpeteer\Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @param \Closure|\Nesk\Puphpeteer\JsFunction $handler
     * @return \Nesk\Puphpeteer\Browser
     */
    public function once(string $type, \Closure|\Nesk\Puphpeteer\JsFunction $handler): \Nesk\Puphpeteer\Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (bool)|null $includeAll
     * @return list<\Nesk\Puphpeteer\Page>
     */
    public function pages(bool|null $includeAll = NULL): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (string)|null $type
     * @return \Nesk\Puphpeteer\Browser
     */
    public function removeAllListeners(string|null $type = NULL): \Nesk\Puphpeteer\Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $screenId
     * @return void
     */
    public function removeScreen(string $screenId): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return list<array{availHeight: int|float, availLeft: int|float, availTop: int|float, availWidth: int|float, colorDepth: int|float, devicePixelRatio: int|float, height: int|float, id: string, isExtended: bool, isInternal: bool, isPrimary: bool, label: string, left: int|float, orientation: array{angle: int|float, type: string}, top: int|float, width: int|float}>
     */
    public function screens(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param array{domain: string, expires?: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, path?: string, priority?: "Low"|"Medium"|"High", sameParty?: bool, sameSite?: "Strict"|"Lax"|"None", secure?: bool, sourceScheme?: "Unset"|"NonSecure"|"Secure", value: string} ...$cookies
     * @return void
     */
    public function setCookie(mixed ...$cookies): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $cookies));
    }
    /**
     * @param string $windowId
     * @param array{height?: int|float, left?: int|float, top?: int|float, width?: int|float, windowState?: "normal"|"minimized"|"maximized"|"fullscreen"} $windowBounds
     * @return void
     */
    public function setWindowBounds(string $windowId, array $windowBounds): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return \Nesk\Puphpeteer\Target
     */
    public function target(): \Nesk\Puphpeteer\Target
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return list<\Nesk\Puphpeteer\Target>
     */
    public function targets(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $id
     * @return void
     */
    public function uninstallExtension(string $id): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function userAgent(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function version(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param \Closure(\Nesk\Puphpeteer\Target):bool $predicate
     * @param (array{signal?: never, timeout?: int|float})|null $options
     * @return \Nesk\Puphpeteer\Target
     */
    public function waitForTarget(\Closure $predicate, array|null $options = NULL): \Nesk\Puphpeteer\Target
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function wsEndpoint(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
