<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class CDPSession extends \Nesk\Puphpeteer\RemoteObject
{
    /**
     * @return void
     */
    public function detach(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @var bool
     */
    public bool $detached {
        get {
            return $this->getRemote('detached');
        }
    }
    /**
     * @return string
     */
    public function id(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @return int|float
     */
    public function listenerCount(string $type): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @param (\Closure|\Nesk\Puphpeteer\JsFunction)|null $handler
     * @return \Nesk\Puphpeteer\CDPSession
     */
    public function off(string $type, \Closure|\Nesk\Puphpeteer\JsFunction|null $handler = NULL): \Nesk\Puphpeteer\CDPSession
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @param \Closure|\Nesk\Puphpeteer\JsFunction $handler
     * @return \Nesk\Puphpeteer\CDPSession
     */
    public function on(string $type, \Closure|\Nesk\Puphpeteer\JsFunction $handler): \Nesk\Puphpeteer\CDPSession
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @param \Closure|\Nesk\Puphpeteer\JsFunction $handler
     * @return \Nesk\Puphpeteer\CDPSession
     */
    public function once(string $type, \Closure|\Nesk\Puphpeteer\JsFunction $handler): \Nesk\Puphpeteer\CDPSession
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (string)|null $type
     * @return \Nesk\Puphpeteer\CDPSession
     */
    public function removeAllListeners(string|null $type = NULL): \Nesk\Puphpeteer\CDPSession
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
