<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class ConsoleMessage extends \Nesk\Puphpeteer\RemoteObject
{
    /**
     * @return list<\Nesk\Puphpeteer\JSHandle>
     */
    public function args(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return array{columnNumber?: int|float, lineNumber?: int|float, url?: string}
     */
    public function location(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return list<array{columnNumber?: int|float, lineNumber?: int|float, url?: string}>
     */
    public function stackTrace(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function text(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return "log"|"debug"|"info"|"error"|"warn"|"dir"|"dirxml"|"table"|"trace"|"clear"|"startGroup"|"startGroupCollapsed"|"endGroup"|"assert"|"profile"|"profileEnd"|"count"|"timeEnd"|"verbose"
     */
    public function type(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
