<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class Dialog extends \Nesk\Puphpeteer\RemoteObject
{
    /**
     * @param (string)|null $promptText
     * @return void
     */
    public function accept(string|null $promptText = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function defaultValue(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return void
     */
    public function dismiss(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @var bool
     */
    public bool $handled {
        get {
            return $this->getRemote('handled');
        }
    }
    /**
     * @return string
     */
    public function message(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return "prompt"|"alert"|"confirm"|"beforeunload"
     */
    public function type(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
