<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class ElementHandle extends \Nesk\Puphpeteer\JSHandle
{
    /**
     * @param mixed $selector
     * @return \Nesk\Puphpeteer\ElementHandle|null
     */
    public function querySelector(mixed $selector): mixed
    {
        return $this->invokeRemote('$', func_get_args());
    }
    /**
     * @param mixed $selector
     * @param (array{isolate: bool})|null $options
     * @return list<\Nesk\Puphpeteer\ElementHandle>
     */
    public function querySelectorAll(mixed $selector, array|null $options = NULL): mixed
    {
        return $this->invokeRemote('$$', func_get_args());
    }
    /**
     * @param mixed $selector
     * @param string|\Nesk\Puphpeteer\JsFunction $pageFunction
     * @param mixed ...$args
     * @return mixed
     */
    public function querySelectorAllEval(mixed $selector, string|\Nesk\Puphpeteer\JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote('$$eval', self::mergeNamedArguments(func_get_args(), $args));
    }
    /**
     * @param mixed $selector
     * @param string|\Nesk\Puphpeteer\JsFunction $pageFunction
     * @param mixed ...$args
     * @return mixed
     */
    public function querySelectorEval(mixed $selector, string|\Nesk\Puphpeteer\JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote('$eval', self::mergeNamedArguments(func_get_args(), $args));
    }
    /**
     * @return null|\Nesk\Puphpeteer\ElementHandle
     */
    #[\Override]
    public function asElement(): null|\Nesk\Puphpeteer\ElementHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param array{creditCard: array{number: string, name: string, expiryMonth: string, expiryYear: string, cvc: string}} $data
     * @return void
     */
    public function autofill(array $data): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return int|float
     */
    public function backendNodeId(): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|array{height: int|float, width: int|float, x: int|float, y: int|float}
     */
    public function boundingBox(): null|array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|array{border: array{0: array{x: int|float, y: int|float}, 1: array{x: int|float, y: int|float}, 2: array{x: int|float, y: int|float}, 3: array{x: int|float, y: int|float}}, content: array{0: array{x: int|float, y: int|float}, 1: array{x: int|float, y: int|float}, 2: array{x: int|float, y: int|float}, 3: array{x: int|float, y: int|float}}, height: int|float, margin: array{0: array{x: int|float, y: int|float}, 1: array{x: int|float, y: int|float}, 2: array{x: int|float, y: int|float}, 3: array{x: int|float, y: int|float}}, padding: array{0: array{x: int|float, y: int|float}, 1: array{x: int|float, y: int|float}, 2: array{x: int|float, y: int|float}, 3: array{x: int|float, y: int|float}}, width: int|float}
     */
    public function boxModel(): null|array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{offset?: array{x: int|float, y: int|float}, debugHighlight?: bool, delay?: int|float, count?: int|float, button?: "left"|"right"|"middle"|"back"|"forward", clickCount?: int|float})|null $options
     * @return void
     */
    public function click(array|null $options = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{x: int|float, y: int|float})|null $offset
     * @return array{x: int|float, y: int|float}
     */
    public function clickablePoint(array|null $offset = NULL): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return void
     */
    #[\Override]
    public function dispose(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param array{x: int|float, y: int|float}|\Nesk\Puphpeteer\ElementHandle $target
     * @return null|array{dragOperationsMask: int|float, files?: list<string>, items: list<array{baseURL?: string, data: string, mimeType: string, title?: string}>}
     */
    public function drag(array|\Nesk\Puphpeteer\ElementHandle $target): null|array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param \Nesk\Puphpeteer\ElementHandle $target
     * @param (array{delay: int|float})|null $options
     * @return void
     */
    public function dragAndDrop(\Nesk\Puphpeteer\ElementHandle $target, array|null $options = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{dragOperationsMask: int|float, files?: list<string>, items: list<array{baseURL?: string, data: string, mimeType: string, title?: string}>})|null $data
     * @return void
     */
    public function dragEnter(array|null $data = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{dragOperationsMask: int|float, files?: list<string>, items: list<array{baseURL?: string, data: string, mimeType: string, title?: string}>})|null $data
     * @return void
     */
    public function dragOver(array|null $data = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string|\Nesk\Puphpeteer\JsFunction $pageFunction
     * @param mixed ...$args
     * @return mixed
     */
    #[\Override]
    public function evaluate(string|\Nesk\Puphpeteer\JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }
    /**
     * @param string|\Nesk\Puphpeteer\JsFunction $pageFunction
     * @param mixed ...$args
     * @return \Nesk\Puphpeteer\JSHandle
     */
    #[\Override]
    public function evaluateHandle(string|\Nesk\Puphpeteer\JsFunction $pageFunction, mixed ...$args): \Nesk\Puphpeteer\JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }
    /**
     * @return void
     */
    public function focus(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @var \Nesk\Puphpeteer\Frame
     */
    public \Nesk\Puphpeteer\Frame $frame {
        get {
            return $this->getRemote('frame');
        }
    }
    /**
     * @param string $propertyName
     * @return \Nesk\Puphpeteer\JSHandle
     */
    #[\Override]
    public function getProperty(string $propertyName): \Nesk\Puphpeteer\JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return void
     */
    public function hover(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return bool
     */
    public function isHidden(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{threshold?: int|float})|null $options
     * @return bool
     */
    public function isIntersectingViewport(array|null $options = NULL): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return bool
     */
    public function isVisible(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return mixed
     */
    #[\Override]
    public function jsonValue(): mixed
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param "*"|" "|"\n"|"\r"|"a"|"b"|"i"|"p"|"q"|"s"|"u"|"g"|"0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"|"Power"|"Eject"|"Abort"|"Help"|"Backspace"|"Tab"|"Numpad5"|"NumpadEnter"|"Enter"|"ShiftLeft"|"ShiftRight"|"ControlLeft"|"ControlRight"|"AltLeft"|"AltRight"|"Pause"|"CapsLock"|"Escape"|"Convert"|"NonConvert"|"Space"|"Numpad9"|"PageUp"|"Numpad3"|"PageDown"|"End"|"Numpad1"|"Home"|"Numpad7"|"ArrowLeft"|"Numpad4"|"Numpad8"|"ArrowUp"|"ArrowRight"|"Numpad6"|"Numpad2"|"ArrowDown"|"Select"|"Open"|"PrintScreen"|"Insert"|"Numpad0"|"Delete"|"NumpadDecimal"|"Digit0"|"Digit1"|"Digit2"|"Digit3"|"Digit4"|"Digit5"|"Digit6"|"Digit7"|"Digit8"|"Digit9"|"KeyA"|"KeyB"|"KeyC"|"KeyD"|"KeyE"|"KeyF"|"KeyG"|"KeyH"|"KeyI"|"KeyJ"|"KeyK"|"KeyL"|"KeyM"|"KeyN"|"KeyO"|"KeyP"|"KeyQ"|"KeyR"|"KeyS"|"KeyT"|"KeyU"|"KeyV"|"KeyW"|"KeyX"|"KeyY"|"KeyZ"|"MetaLeft"|"MetaRight"|"ContextMenu"|"NumpadMultiply"|"NumpadAdd"|"NumpadSubtract"|"NumpadDivide"|"F1"|"F2"|"F3"|"F4"|"F5"|"F6"|"F7"|"F8"|"F9"|"F10"|"F11"|"F12"|"F13"|"F14"|"F15"|"F16"|"F17"|"F18"|"F19"|"F20"|"F21"|"F22"|"F23"|"F24"|"NumLock"|"ScrollLock"|"AudioVolumeMute"|"AudioVolumeDown"|"AudioVolumeUp"|"MediaTrackNext"|"MediaTrackPrevious"|"MediaStop"|"MediaPlayPause"|"Semicolon"|"Equal"|"NumpadEqual"|"Comma"|"Minus"|"Period"|"Slash"|"Backquote"|"BracketLeft"|"Backslash"|"BracketRight"|"Quote"|"AltGraph"|"Props"|"Cancel"|"Clear"|"Shift"|"Control"|"Alt"|"Accept"|"ModeChange"|"Print"|"Execute"|"\u0000"|"c"|"d"|"e"|"f"|"h"|"j"|"k"|"l"|"m"|"n"|"o"|"r"|"t"|"v"|"w"|"x"|"y"|"z"|"Meta"|"+"|"-"|"/"|";"|"="|","|"."|"`"|"["|"\\"|"]"|"'"|"Attn"|"CrSel"|"ExSel"|"EraseEof"|"Play"|"ZoomOut"|")"|"!"|"@"|"#"|"$"|"%"|"^"|"&"|"("|"A"|"B"|"C"|"D"|"E"|"F"|"G"|"H"|"I"|"J"|"K"|"L"|"M"|"N"|"O"|"P"|"Q"|"R"|"S"|"T"|"U"|"V"|"W"|"X"|"Y"|"Z"|":"|"<"|"_"|">"|"?"|"~"|"{"|"|"|"}"|"\""|"SoftLeft"|"SoftRight"|"Camera"|"Call"|"EndCall"|"VolumeDown"|"VolumeUp" $key
     * @param (array{text?: string, commands?: list<string>, delay?: int|float})|null $options
     * @return void
     */
    public function press(string $key, array|null $options = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{optimizeForSpeed?: bool, type?: "png"|"jpeg"|"webp", quality?: int|float, fromSurface?: bool, fullPage?: bool, omitBackground?: bool, path?: string, clip?: array{height: int|float, scale?: int|float, width: int|float, x: int|float, y: int|float}, encoding?: "base64"|"binary", captureBeyondViewport?: bool})|null $options
     * @return string
     */
    public function screenshot(array|null $options = NULL): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return void
     */
    public function scrollIntoView(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string ...$values
     * @return list<string>
     */
    public function select(mixed ...$values): array
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $values));
    }
    /**
     * @return void
     */
    public function tap(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    #[\Override]
    public function toString(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return void
     */
    public function touchEnd(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $text
     * @param (array{delay?: int|float})|null $options
     * @return void
     */
    public function type(string $text, array|null $options = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string ...$paths
     * @return void
     */
    public function uploadFile(mixed ...$paths): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $paths));
    }
    /**
     * @param mixed $selector
     * @param (array{hidden?: bool, signal?: never, timeout?: int|float, visible?: bool})|null $options
     * @return \Nesk\Puphpeteer\ElementHandle|null
     */
    public function waitForSelector(mixed $selector, array|null $options = NULL): mixed
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
