<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class FileChooser extends \Nesk\Puphpeteer\RemoteObject
{
    /**
     * @param list<string> $paths
     * @return void
     */
    public function accept(array $paths): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return void
     */
    public function cancel(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return bool
     */
    public function isMultiple(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
