<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class HTTPResponse extends \Nesk\Puphpeteer\RemoteObject
{
    /**
     * @return string
     */
    public function content(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|\Nesk\Puphpeteer\Frame
     */
    public function frame(): null|\Nesk\Puphpeteer\Frame
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return bool
     */
    public function fromCache(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return bool
     */
    public function fromServiceWorker(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return array<string, string>
     */
    public function headers(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return mixed
     */
    public function json(): mixed
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return bool
     */
    public function ok(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return array{ip?: string, port?: int|float}
     */
    public function remoteAddress(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return \Nesk\Puphpeteer\HTTPRequest
     */
    public function request(): \Nesk\Puphpeteer\HTTPRequest
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|\Nesk\Puphpeteer\SecurityDetails
     */
    public function securityDetails(): null|\Nesk\Puphpeteer\SecurityDetails
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return int|float
     */
    public function status(): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function statusText(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function text(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|array{connectEnd: int|float, connectStart: int|float, dnsEnd: int|float, dnsStart: int|float, proxyEnd: int|float, proxyStart: int|float, pushEnd: int|float, pushStart: int|float, receiveHeadersEnd: int|float, receiveHeadersStart: int|float, requestTime: int|float, sendEnd: int|float, sendStart: int|float, sslEnd: int|float, sslStart: int|float, workerCacheLookupStart?: int|float, workerFetchStart: int|float, workerReady: int|float, workerRespondWithSettled: int|float, workerRouterEvaluationStart?: int|float, workerStart: int|float}
     */
    public function timing(): null|array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function url(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
