<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class HTTPRequest extends \Nesk\Puphpeteer\RemoteObject
{
    /**
     * @param ("aborted"|"accessdenied"|"addressunreachable"|"blockedbyclient"|"blockedbyresponse"|"connectionaborted"|"connectionclosed"|"connectionfailed"|"connectionrefused"|"connectionreset"|"internetdisconnected"|"namenotresolved"|"timedout"|"failed")|null $errorCode
     * @param (int|float)|null $priority
     * @return void
     */
    public function abort(string|null $errorCode = NULL, int|float|null $priority = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|"Failed"|"Aborted"|"TimedOut"|"AccessDenied"|"ConnectionClosed"|"ConnectionReset"|"ConnectionRefused"|"ConnectionAborted"|"ConnectionFailed"|"NameNotResolved"|"InternetDisconnected"|"AddressUnreachable"|"BlockedByClient"|"BlockedByResponse"
     */
    public function abortErrorReason(): null|string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @var \Nesk\Puphpeteer\CDPSession
     */
    public \Nesk\Puphpeteer\CDPSession $client {
        get {
            return $this->getRemote('client');
        }
    }
    /**
     * @param (array{headers?: array<string, string>, method?: string, postData?: string, url?: string})|null $overrides
     * @param (int|float)|null $priority
     * @return void
     */
    public function continue(array|null $overrides = NULL, int|float|null $priority = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return array{headers?: array<string, string>, method?: string, postData?: string, url?: string}
     */
    public function continueRequestOverrides(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param \Closure():mixed $pendingHandler
     * @return void
     */
    public function enqueueInterceptAction(\Closure $pendingHandler): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|array{errorText: string}
     */
    public function failure(): null|array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|string
     */
    public function fetchPostData(): null|string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return void
     */
    public function finalizeInterceptions(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|\Nesk\Puphpeteer\Frame
     */
    public function frame(): null|\Nesk\Puphpeteer\Frame
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return bool
     */
    public function hasPostData(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return array<string, string>
     */
    public function headers(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return array{action: "abort"|"respond"|"continue"|"disabled"|"none"|"already-handled", priority?: int|float}
     */
    public function interceptResolutionState(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return bool
     */
    public function isInterceptResolutionHandled(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return bool
     */
    public function isNavigationRequest(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function method(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|string
     */
    public function postData(): null|string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return list<\Nesk\Puphpeteer\HTTPRequest>
     */
    public function redirectChain(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return "script" | "image" | "document" | "stylesheet" | "media" | "font" | "texttrack" | "xhr" | "fetch" | "prefetch" | "eventsource" | "websocket" | "manifest" | "signedexchange" | "ping" | "cspviolationreport" | "preflight" | "fedcm" | "other"
     */
    public function resourceType(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param array{status?: int|float, headers?: array<string, mixed>, contentType?: string, body?: string} $response
     * @param (int|float)|null $priority
     * @return void
     */
    public function respond(array $response, int|float|null $priority = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|\Nesk\Puphpeteer\HTTPResponse
     */
    public function response(): null|\Nesk\Puphpeteer\HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|array{status?: int|float, headers?: array<string, mixed>, contentType?: string, body?: string}
     */
    public function responseForRequest(): null|array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function url(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
