<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class JSHandle extends \Nesk\Puphpeteer\RemoteObject
{
    /**
     * @return null|\Nesk\Puphpeteer\ElementHandle
     */
    public function asElement(): null|\Nesk\Puphpeteer\ElementHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return void
     */
    public function dispose(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string|\Nesk\Puphpeteer\JsFunction $pageFunction
     * @param mixed ...$args
     * @return mixed
     */
    public function evaluate(string|\Nesk\Puphpeteer\JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }
    /**
     * @param string|\Nesk\Puphpeteer\JsFunction $pageFunction
     * @param mixed ...$args
     * @return \Nesk\Puphpeteer\JSHandle
     */
    public function evaluateHandle(string|\Nesk\Puphpeteer\JsFunction $pageFunction, mixed ...$args): \Nesk\Puphpeteer\JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }
    /**
     * @param string $propertyName
     * @return \Nesk\Puphpeteer\JSHandle
     */
    public function getProperty(string $propertyName): \Nesk\Puphpeteer\JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return mixed
     */
    public function jsonValue(): mixed
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function toString(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
