<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class Keyboard extends \Nesk\Puphpeteer\RemoteObject
{
    /**
     * @param "*"|" "|"\n"|"\r"|"a"|"b"|"i"|"p"|"q"|"s"|"u"|"g"|"0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"|"Power"|"Eject"|"Abort"|"Help"|"Backspace"|"Tab"|"Numpad5"|"NumpadEnter"|"Enter"|"ShiftLeft"|"ShiftRight"|"ControlLeft"|"ControlRight"|"AltLeft"|"AltRight"|"Pause"|"CapsLock"|"Escape"|"Convert"|"NonConvert"|"Space"|"Numpad9"|"PageUp"|"Numpad3"|"PageDown"|"End"|"Numpad1"|"Home"|"Numpad7"|"ArrowLeft"|"Numpad4"|"Numpad8"|"ArrowUp"|"ArrowRight"|"Numpad6"|"Numpad2"|"ArrowDown"|"Select"|"Open"|"PrintScreen"|"Insert"|"Numpad0"|"Delete"|"NumpadDecimal"|"Digit0"|"Digit1"|"Digit2"|"Digit3"|"Digit4"|"Digit5"|"Digit6"|"Digit7"|"Digit8"|"Digit9"|"KeyA"|"KeyB"|"KeyC"|"KeyD"|"KeyE"|"KeyF"|"KeyG"|"KeyH"|"KeyI"|"KeyJ"|"KeyK"|"KeyL"|"KeyM"|"KeyN"|"KeyO"|"KeyP"|"KeyQ"|"KeyR"|"KeyS"|"KeyT"|"KeyU"|"KeyV"|"KeyW"|"KeyX"|"KeyY"|"KeyZ"|"MetaLeft"|"MetaRight"|"ContextMenu"|"NumpadMultiply"|"NumpadAdd"|"NumpadSubtract"|"NumpadDivide"|"F1"|"F2"|"F3"|"F4"|"F5"|"F6"|"F7"|"F8"|"F9"|"F10"|"F11"|"F12"|"F13"|"F14"|"F15"|"F16"|"F17"|"F18"|"F19"|"F20"|"F21"|"F22"|"F23"|"F24"|"NumLock"|"ScrollLock"|"AudioVolumeMute"|"AudioVolumeDown"|"AudioVolumeUp"|"MediaTrackNext"|"MediaTrackPrevious"|"MediaStop"|"MediaPlayPause"|"Semicolon"|"Equal"|"NumpadEqual"|"Comma"|"Minus"|"Period"|"Slash"|"Backquote"|"BracketLeft"|"Backslash"|"BracketRight"|"Quote"|"AltGraph"|"Props"|"Cancel"|"Clear"|"Shift"|"Control"|"Alt"|"Accept"|"ModeChange"|"Print"|"Execute"|"\u0000"|"c"|"d"|"e"|"f"|"h"|"j"|"k"|"l"|"m"|"n"|"o"|"r"|"t"|"v"|"w"|"x"|"y"|"z"|"Meta"|"+"|"-"|"/"|";"|"="|","|"."|"`"|"["|"\\"|"]"|"'"|"Attn"|"CrSel"|"ExSel"|"EraseEof"|"Play"|"ZoomOut"|")"|"!"|"@"|"#"|"$"|"%"|"^"|"&"|"("|"A"|"B"|"C"|"D"|"E"|"F"|"G"|"H"|"I"|"J"|"K"|"L"|"M"|"N"|"O"|"P"|"Q"|"R"|"S"|"T"|"U"|"V"|"W"|"X"|"Y"|"Z"|":"|"<"|"_"|">"|"?"|"~"|"{"|"|"|"}"|"\""|"SoftLeft"|"SoftRight"|"Camera"|"Call"|"EndCall"|"VolumeDown"|"VolumeUp" $key
     * @param (array{text?: string, commands?: list<string>})|null $options
     * @return void
     */
    public function down(string $key, array|null $options = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param "*"|" "|"\n"|"\r"|"a"|"b"|"i"|"p"|"q"|"s"|"u"|"g"|"0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"|"Power"|"Eject"|"Abort"|"Help"|"Backspace"|"Tab"|"Numpad5"|"NumpadEnter"|"Enter"|"ShiftLeft"|"ShiftRight"|"ControlLeft"|"ControlRight"|"AltLeft"|"AltRight"|"Pause"|"CapsLock"|"Escape"|"Convert"|"NonConvert"|"Space"|"Numpad9"|"PageUp"|"Numpad3"|"PageDown"|"End"|"Numpad1"|"Home"|"Numpad7"|"ArrowLeft"|"Numpad4"|"Numpad8"|"ArrowUp"|"ArrowRight"|"Numpad6"|"Numpad2"|"ArrowDown"|"Select"|"Open"|"PrintScreen"|"Insert"|"Numpad0"|"Delete"|"NumpadDecimal"|"Digit0"|"Digit1"|"Digit2"|"Digit3"|"Digit4"|"Digit5"|"Digit6"|"Digit7"|"Digit8"|"Digit9"|"KeyA"|"KeyB"|"KeyC"|"KeyD"|"KeyE"|"KeyF"|"KeyG"|"KeyH"|"KeyI"|"KeyJ"|"KeyK"|"KeyL"|"KeyM"|"KeyN"|"KeyO"|"KeyP"|"KeyQ"|"KeyR"|"KeyS"|"KeyT"|"KeyU"|"KeyV"|"KeyW"|"KeyX"|"KeyY"|"KeyZ"|"MetaLeft"|"MetaRight"|"ContextMenu"|"NumpadMultiply"|"NumpadAdd"|"NumpadSubtract"|"NumpadDivide"|"F1"|"F2"|"F3"|"F4"|"F5"|"F6"|"F7"|"F8"|"F9"|"F10"|"F11"|"F12"|"F13"|"F14"|"F15"|"F16"|"F17"|"F18"|"F19"|"F20"|"F21"|"F22"|"F23"|"F24"|"NumLock"|"ScrollLock"|"AudioVolumeMute"|"AudioVolumeDown"|"AudioVolumeUp"|"MediaTrackNext"|"MediaTrackPrevious"|"MediaStop"|"MediaPlayPause"|"Semicolon"|"Equal"|"NumpadEqual"|"Comma"|"Minus"|"Period"|"Slash"|"Backquote"|"BracketLeft"|"Backslash"|"BracketRight"|"Quote"|"AltGraph"|"Props"|"Cancel"|"Clear"|"Shift"|"Control"|"Alt"|"Accept"|"ModeChange"|"Print"|"Execute"|"\u0000"|"c"|"d"|"e"|"f"|"h"|"j"|"k"|"l"|"m"|"n"|"o"|"r"|"t"|"v"|"w"|"x"|"y"|"z"|"Meta"|"+"|"-"|"/"|";"|"="|","|"."|"`"|"["|"\\"|"]"|"'"|"Attn"|"CrSel"|"ExSel"|"EraseEof"|"Play"|"ZoomOut"|")"|"!"|"@"|"#"|"$"|"%"|"^"|"&"|"("|"A"|"B"|"C"|"D"|"E"|"F"|"G"|"H"|"I"|"J"|"K"|"L"|"M"|"N"|"O"|"P"|"Q"|"R"|"S"|"T"|"U"|"V"|"W"|"X"|"Y"|"Z"|":"|"<"|"_"|">"|"?"|"~"|"{"|"|"|"}"|"\""|"SoftLeft"|"SoftRight"|"Camera"|"Call"|"EndCall"|"VolumeDown"|"VolumeUp" $key
     * @param (array{text?: string, commands?: list<string>, delay?: int|float})|null $options
     * @return void
     */
    public function press(string $key, array|null $options = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $char
     * @return void
     */
    public function sendCharacter(string $char): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $text
     * @param (array{delay?: int|float})|null $options
     * @return void
     */
    public function type(string $text, array|null $options = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param "*"|" "|"\n"|"\r"|"a"|"b"|"i"|"p"|"q"|"s"|"u"|"g"|"0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"|"Power"|"Eject"|"Abort"|"Help"|"Backspace"|"Tab"|"Numpad5"|"NumpadEnter"|"Enter"|"ShiftLeft"|"ShiftRight"|"ControlLeft"|"ControlRight"|"AltLeft"|"AltRight"|"Pause"|"CapsLock"|"Escape"|"Convert"|"NonConvert"|"Space"|"Numpad9"|"PageUp"|"Numpad3"|"PageDown"|"End"|"Numpad1"|"Home"|"Numpad7"|"ArrowLeft"|"Numpad4"|"Numpad8"|"ArrowUp"|"ArrowRight"|"Numpad6"|"Numpad2"|"ArrowDown"|"Select"|"Open"|"PrintScreen"|"Insert"|"Numpad0"|"Delete"|"NumpadDecimal"|"Digit0"|"Digit1"|"Digit2"|"Digit3"|"Digit4"|"Digit5"|"Digit6"|"Digit7"|"Digit8"|"Digit9"|"KeyA"|"KeyB"|"KeyC"|"KeyD"|"KeyE"|"KeyF"|"KeyG"|"KeyH"|"KeyI"|"KeyJ"|"KeyK"|"KeyL"|"KeyM"|"KeyN"|"KeyO"|"KeyP"|"KeyQ"|"KeyR"|"KeyS"|"KeyT"|"KeyU"|"KeyV"|"KeyW"|"KeyX"|"KeyY"|"KeyZ"|"MetaLeft"|"MetaRight"|"ContextMenu"|"NumpadMultiply"|"NumpadAdd"|"NumpadSubtract"|"NumpadDivide"|"F1"|"F2"|"F3"|"F4"|"F5"|"F6"|"F7"|"F8"|"F9"|"F10"|"F11"|"F12"|"F13"|"F14"|"F15"|"F16"|"F17"|"F18"|"F19"|"F20"|"F21"|"F22"|"F23"|"F24"|"NumLock"|"ScrollLock"|"AudioVolumeMute"|"AudioVolumeDown"|"AudioVolumeUp"|"MediaTrackNext"|"MediaTrackPrevious"|"MediaStop"|"MediaPlayPause"|"Semicolon"|"Equal"|"NumpadEqual"|"Comma"|"Minus"|"Period"|"Slash"|"Backquote"|"BracketLeft"|"Backslash"|"BracketRight"|"Quote"|"AltGraph"|"Props"|"Cancel"|"Clear"|"Shift"|"Control"|"Alt"|"Accept"|"ModeChange"|"Print"|"Execute"|"\u0000"|"c"|"d"|"e"|"f"|"h"|"j"|"k"|"l"|"m"|"n"|"o"|"r"|"t"|"v"|"w"|"x"|"y"|"z"|"Meta"|"+"|"-"|"/"|";"|"="|","|"."|"`"|"["|"\\"|"]"|"'"|"Attn"|"CrSel"|"ExSel"|"EraseEof"|"Play"|"ZoomOut"|")"|"!"|"@"|"#"|"$"|"%"|"^"|"&"|"("|"A"|"B"|"C"|"D"|"E"|"F"|"G"|"H"|"I"|"J"|"K"|"L"|"M"|"N"|"O"|"P"|"Q"|"R"|"S"|"T"|"U"|"V"|"W"|"X"|"Y"|"Z"|":"|"<"|"_"|">"|"?"|"~"|"{"|"|"|"}"|"\""|"SoftLeft"|"SoftRight"|"Camera"|"Call"|"EndCall"|"VolumeDown"|"VolumeUp" $key
     * @return void
     */
    public function up(string $key): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
