<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class Page extends \Nesk\Puphpeteer\RemoteObject
{
    /**
     * @param mixed $selector
     * @return \Nesk\Puphpeteer\ElementHandle|null
     */
    public function querySelector(mixed $selector): mixed
    {
        return $this->invokeRemote('$', func_get_args());
    }
    /**
     * @param mixed $selector
     * @param (array{isolate: bool})|null $options
     * @return list<\Nesk\Puphpeteer\ElementHandle>
     */
    public function querySelectorAll(mixed $selector, array|null $options = NULL): mixed
    {
        return $this->invokeRemote('$$', func_get_args());
    }
    /**
     * @param mixed $selector
     * @param string|\Nesk\Puphpeteer\JsFunction $pageFunction
     * @param mixed ...$args
     * @return mixed
     */
    public function querySelectorAllEval(mixed $selector, string|\Nesk\Puphpeteer\JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote('$$eval', self::mergeNamedArguments(func_get_args(), $args));
    }
    /**
     * @param mixed $selector
     * @param string|\Nesk\Puphpeteer\JsFunction $pageFunction
     * @param mixed ...$args
     * @return mixed
     */
    public function querySelectorEval(mixed $selector, string|\Nesk\Puphpeteer\JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote('$eval', self::mergeNamedArguments(func_get_args(), $args));
    }
    /**
     * @var \Nesk\Puphpeteer\Accessibility
     */
    public \Nesk\Puphpeteer\Accessibility $accessibility {
        get {
            return $this->getRemote('accessibility');
        }
    }
    /**
     * @param array{content?: string, id?: string, path?: string, type?: string, url?: string} $options
     * @return \Nesk\Puphpeteer\ElementHandle
     */
    public function addScriptTag(array $options): \Nesk\Puphpeteer\ElementHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param null|array{password: string, username: string} $credentials
     * @return void
     */
    public function authenticate(null|array $credentials): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return void
     */
    public function bringToFront(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return \Nesk\Puphpeteer\Browser
     */
    public function browser(): \Nesk\Puphpeteer\Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return \Nesk\Puphpeteer\BrowserContext
     */
    public function browserContext(): \Nesk\Puphpeteer\BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $selector
     * @param (array{offset?: array{x: int|float, y: int|float}, debugHighlight?: bool, delay?: int|float, count?: int|float, button?: "left"|"right"|"middle"|"back"|"forward", clickCount?: int|float})|null $options
     * @return void
     */
    public function click(string $selector, array|null $options = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{runBeforeUnload?: bool})|null $options
     * @return void
     */
    public function close(array|null $options = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function content(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string ...$urls
     * @return list<array{domain: string, expires: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, partitionKeyOpaque?: bool, path: string, priority?: "Low"|"Medium"|"High", sameParty?: bool, sameSite?: "Strict"|"Lax"|"None", secure: bool, session: bool, size: int|float, sourceScheme?: "Unset"|"NonSecure"|"Secure", value: string}>
     */
    public function cookies(mixed ...$urls): array
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $urls));
    }
    /**
     * @var \Nesk\Puphpeteer\Coverage
     */
    public \Nesk\Puphpeteer\Coverage $coverage {
        get {
            return $this->getRemote('coverage');
        }
    }
    /**
     * @return \Nesk\Puphpeteer\CDPSession
     */
    public function createCDPSession(): \Nesk\Puphpeteer\CDPSession
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param array{domain?: string, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, path?: string, url?: string} ...$cookies
     * @return void
     */
    public function deleteCookie(mixed ...$cookies): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $cookies));
    }
    /**
     * @param array{userAgent: string, viewport: array{deviceScaleFactor?: int|float, hasTouch?: bool, height: int|float, isLandscape?: bool, isMobile?: bool, width: int|float}} $device
     * @return void
     */
    public function emulate(array $device): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param null|int|float $factor
     * @return void
     */
    public function emulateCPUThrottling(null|int|float $factor): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param bool $enabled
     * @return void
     */
    public function emulateFocusedPage(bool $enabled): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{isUserActive: bool, isScreenUnlocked: bool})|null $overrides
     * @return void
     */
    public function emulateIdleState(array|null $overrides = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (list<array{name: string, value: string}>)|null $features
     * @return void
     */
    public function emulateMediaFeatures(array|null $features = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (string)|null $type
     * @return void
     */
    public function emulateMediaType(string|null $type = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param null|array{download: int|float, latency: int|float, offline?: bool, upload: int|float} $networkConditions
     * @return void
     */
    public function emulateNetworkConditions(null|array $networkConditions): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (string)|null $timezoneId
     * @return void
     */
    public function emulateTimezone(string|null $timezoneId = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param ("none"|"blurredVision"|"reducedContrast"|"achromatopsia"|"deuteranopia"|"protanopia"|"tritanopia")|null $type
     * @return void
     */
    public function emulateVisionDeficiency(string|null $type = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string|\Nesk\Puphpeteer\JsFunction $pageFunction
     * @param mixed ...$args
     * @return mixed
     */
    public function evaluate(string|\Nesk\Puphpeteer\JsFunction $pageFunction, mixed ...$args): mixed
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }
    /**
     * @param string|\Nesk\Puphpeteer\JsFunction $pageFunction
     * @param mixed ...$args
     * @return \Nesk\Puphpeteer\JSHandle
     */
    public function evaluateHandle(string|\Nesk\Puphpeteer\JsFunction $pageFunction, mixed ...$args): \Nesk\Puphpeteer\JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }
    /**
     * @param string|\Nesk\Puphpeteer\JsFunction $pageFunction
     * @param mixed ...$args
     * @return array{identifier: string}
     */
    public function evaluateOnNewDocument(string|\Nesk\Puphpeteer\JsFunction $pageFunction, mixed ...$args): array
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }
    /**
     * @param string $name
     * @param \Closure $pptrFunction
     * @return void
     */
    public function exposeFunction(string $name, \Closure $pptrFunction): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $selector
     * @return void
     */
    public function focus(string $selector): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return list<\Nesk\Puphpeteer\Frame>
     */
    public function frames(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return int|float
     */
    public function getDefaultNavigationTimeout(): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return int|float
     */
    public function getDefaultTimeout(): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{signal?: never, timeout?: int|float, waitUntil?: "load"|"domcontentloaded"|"networkidle0"|"networkidle2"|list<"load"|"domcontentloaded"|"networkidle0"|"networkidle2">})|null $options
     * @return null|\Nesk\Puphpeteer\HTTPResponse
     */
    public function goBack(array|null $options = NULL): null|\Nesk\Puphpeteer\HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{signal?: never, timeout?: int|float, waitUntil?: "load"|"domcontentloaded"|"networkidle0"|"networkidle2"|list<"load"|"domcontentloaded"|"networkidle0"|"networkidle2">})|null $options
     * @return null|\Nesk\Puphpeteer\HTTPResponse
     */
    public function goForward(array|null $options = NULL): null|\Nesk\Puphpeteer\HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $url
     * @param (array{referer?: string, referrerPolicy?: string, signal?: never, timeout?: int|float, waitUntil?: "load"|"domcontentloaded"|"networkidle0"|"networkidle2"|list<"load"|"domcontentloaded"|"networkidle0"|"networkidle2">})|null $options
     * @return null|\Nesk\Puphpeteer\HTTPResponse
     */
    public function goto(string $url, array|null $options = NULL): null|\Nesk\Puphpeteer\HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $selector
     * @return void
     */
    public function hover(string $selector): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return bool
     */
    public function isClosed(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return bool
     */
    public function isDragInterceptionEnabled(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return bool
     */
    public function isJavaScriptEnabled(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return bool
     */
    public function isServiceWorkerBypassed(): bool
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @var \Nesk\Puphpeteer\Keyboard
     */
    public \Nesk\Puphpeteer\Keyboard $keyboard {
        get {
            return $this->getRemote('keyboard');
        }
    }
    /**
     * @param string $type
     * @return int|float
     */
    public function listenerCount(string $type): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return \Nesk\Puphpeteer\Frame
     */
    public function mainFrame(): \Nesk\Puphpeteer\Frame
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return array{Documents?: int|float, Frames?: int|float, JSEventListeners?: int|float, JSHeapTotalSize?: int|float, JSHeapUsedSize?: int|float, LayoutCount?: int|float, LayoutDuration?: int|float, Nodes?: int|float, RecalcStyleCount?: int|float, RecalcStyleDuration?: int|float, ScriptDuration?: int|float, TaskDuration?: int|float, Timestamp?: int|float}
     */
    public function metrics(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @var \Nesk\Puphpeteer\Mouse
     */
    public \Nesk\Puphpeteer\Mouse $mouse {
        get {
            return $this->getRemote('mouse');
        }
    }
    /**
     * @param string $type
     * @param (\Closure|\Nesk\Puphpeteer\JsFunction)|null $handler
     * @return \Nesk\Puphpeteer\Page
     */
    public function off(string $type, \Closure|\Nesk\Puphpeteer\JsFunction|null $handler = NULL): \Nesk\Puphpeteer\Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @param \Closure|\Nesk\Puphpeteer\JsFunction $handler
     * @return \Nesk\Puphpeteer\Page
     */
    public function on(string $type, \Closure|\Nesk\Puphpeteer\JsFunction $handler): \Nesk\Puphpeteer\Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @param \Closure|\Nesk\Puphpeteer\JsFunction $handler
     * @return \Nesk\Puphpeteer\Page
     */
    public function once(string $type, \Closure|\Nesk\Puphpeteer\JsFunction $handler): \Nesk\Puphpeteer\Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return \Nesk\Puphpeteer\Page
     */
    public function openDevTools(): \Nesk\Puphpeteer\Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{displayHeaderFooter?: bool, footerTemplate?: string, format?: "letter"|"legal"|"tabloid"|"ledger"|"a0"|"a1"|"a2"|"a3"|"a4"|"a5"|"a6"|"LETTER"|"LEGAL"|"TABLOID"|"LEDGER"|"A0"|"A1"|"A2"|"A3"|"A4"|"A5"|"A6"|"Letter"|"Legal"|"Tabloid"|"Ledger", headerTemplate?: string, height?: string|int|float, landscape?: bool, margin?: array{bottom?: string|int|float, left?: string|int|float, right?: string|int|float, top?: string|int|float}, omitBackground?: bool, outline?: bool, pageRanges?: string, path?: string, preferCSSPageSize?: bool, printBackground?: bool, scale?: int|float, tagged?: bool, timeout?: int|float, waitForFonts?: bool, width?: string|int|float})|null $options
     * @return string
     */
    public function pdf(array|null $options = NULL): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param \Nesk\Puphpeteer\JSHandle $prototypeHandle
     * @return \Nesk\Puphpeteer\JSHandle
     */
    public function queryObjects(\Nesk\Puphpeteer\JSHandle $prototypeHandle): \Nesk\Puphpeteer\JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{ignoreCache?: bool, signal?: never, timeout?: int|float, waitUntil?: "load"|"domcontentloaded"|"networkidle0"|"networkidle2"|list<"load"|"domcontentloaded"|"networkidle0"|"networkidle2">})|null $options
     * @return null|\Nesk\Puphpeteer\HTTPResponse
     */
    public function reload(array|null $options = NULL): null|\Nesk\Puphpeteer\HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (string)|null $type
     * @return \Nesk\Puphpeteer\Page
     */
    public function removeAllListeners(string|null $type = NULL): \Nesk\Puphpeteer\Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $name
     * @return void
     */
    public function removeExposedFunction(string $name): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $identifier
     * @return void
     */
    public function removeScriptToEvaluateOnNewDocument(string $identifier): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param array{contentWidth: int|float, contentHeight: int|float} $params
     * @return void
     */
    public function resize(array $params): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{optimizeForSpeed?: bool, type?: "png"|"jpeg"|"webp", quality?: int|float, fromSurface?: bool, fullPage?: bool, omitBackground?: bool, path?: string, clip?: array{height: int|float, scale?: int|float, width: int|float, x: int|float, y: int|float}, encoding?: "base64"|"binary", captureBeyondViewport?: bool})|null $options
     * @return string
     */
    public function screenshot(array|null $options = NULL): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $selector
     * @param string ...$values
     * @return list<string>
     */
    public function select(string $selector, mixed ...$values): array
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $values));
    }
    /**
     * @param bool $enabled
     * @return void
     */
    public function setBypassCSP(bool $enabled): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param bool $bypass
     * @return void
     */
    public function setBypassServiceWorker(bool $bypass): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (bool)|null $enabled
     * @return void
     */
    public function setCacheEnabled(bool|null $enabled = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $html
     * @param (array{signal?: never, timeout?: int|float, waitUntil?: "load"|"domcontentloaded"|"networkidle0"|"networkidle2"|list<"load"|"domcontentloaded"|"networkidle0"|"networkidle2">})|null $options
     * @return void
     */
    public function setContent(string $html, array|null $options = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param array{domain?: string, expires?: int|float, httpOnly?: bool, name: string, partitionKey?: string|array{hasCrossSiteAncestor?: bool, sourceOrigin: string}, path?: string, priority?: "Low"|"Medium"|"High", sameParty?: bool, sameSite?: "Strict"|"Lax"|"None", secure?: bool, sourceScheme?: "Unset"|"NonSecure"|"Secure", url?: string, value: string} ...$cookies
     * @return void
     */
    public function setCookie(mixed ...$cookies): void
    {
        $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $cookies));
    }
    /**
     * @param int|float $timeout
     * @return void
     */
    public function setDefaultNavigationTimeout(int|float $timeout): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param int|float $timeout
     * @return void
     */
    public function setDefaultTimeout(int|float $timeout): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param bool $enabled
     * @return void
     */
    public function setDragInterception(bool $enabled): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param array<string, string> $headers
     * @return void
     */
    public function setExtraHTTPHeaders(array $headers): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param array{accuracy?: int|float, latitude: int|float, longitude: int|float} $options
     * @return void
     */
    public function setGeolocation(array $options): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param bool $enabled
     * @return void
     */
    public function setJavaScriptEnabled(bool $enabled): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param bool $enabled
     * @return void
     */
    public function setOfflineMode(bool $enabled): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param bool $value
     * @return void
     */
    public function setRequestInterception(bool $value): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param null|array{deviceScaleFactor?: int|float, hasTouch?: bool, height: int|float, isLandscape?: bool, isMobile?: bool, width: int|float} $viewport
     * @return void
     */
    public function setViewport(null|array $viewport): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $selector
     * @return void
     */
    public function tap(string $selector): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return \Nesk\Puphpeteer\Target
     */
    public function target(): \Nesk\Puphpeteer\Target
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function title(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @var \Nesk\Puphpeteer\Touchscreen
     */
    public \Nesk\Puphpeteer\Touchscreen $touchscreen {
        get {
            return $this->getRemote('touchscreen');
        }
    }
    /**
     * @var \Nesk\Puphpeteer\Tracing
     */
    public \Nesk\Puphpeteer\Tracing $tracing {
        get {
            return $this->getRemote('tracing');
        }
    }
    /**
     * @param string $selector
     * @param string $text
     * @param (array{delay?: int|float})|null $options
     * @return void
     */
    public function type(string $selector, string $text, array|null $options = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function url(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|array{deviceScaleFactor?: int|float, hasTouch?: bool, height: int|float, isLandscape?: bool, isMobile?: bool, width: int|float}
     */
    public function viewport(): null|array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{signal?: never, timeout?: int|float})|null $options
     * @return \Nesk\Puphpeteer\FileChooser
     */
    public function waitForFileChooser(array|null $options = NULL): \Nesk\Puphpeteer\FileChooser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string|\Closure(\Nesk\Puphpeteer\Frame):bool $urlOrPredicate
     * @param (array{signal?: never, timeout?: int|float})|null $options
     * @return \Nesk\Puphpeteer\Frame
     */
    public function waitForFrame(string|\Closure $urlOrPredicate, array|null $options = NULL): \Nesk\Puphpeteer\Frame
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{signal?: never, timeout?: int|float, waitUntil?: "load"|"domcontentloaded"|"networkidle0"|"networkidle2"|list<"load"|"domcontentloaded"|"networkidle0"|"networkidle2">})|null $options
     * @return null|\Nesk\Puphpeteer\HTTPResponse
     */
    public function waitForNavigation(array|null $options = NULL): null|\Nesk\Puphpeteer\HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (array{concurrency?: int|float, idleTime?: int|float, signal?: never, timeout?: int|float})|null $options
     * @return void
     */
    public function waitForNetworkIdle(array|null $options = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string|\Closure(\Nesk\Puphpeteer\HTTPRequest):bool $urlOrPredicate
     * @param (array{signal?: never, timeout?: int|float})|null $options
     * @return \Nesk\Puphpeteer\HTTPRequest
     */
    public function waitForRequest(string|\Closure $urlOrPredicate, array|null $options = NULL): \Nesk\Puphpeteer\HTTPRequest
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string|\Closure(\Nesk\Puphpeteer\HTTPResponse):bool $urlOrPredicate
     * @param (array{signal?: never, timeout?: int|float})|null $options
     * @return \Nesk\Puphpeteer\HTTPResponse
     */
    public function waitForResponse(string|\Closure $urlOrPredicate, array|null $options = NULL): \Nesk\Puphpeteer\HTTPResponse
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param mixed $selector
     * @param (array{hidden?: bool, signal?: never, timeout?: int|float, visible?: bool})|null $options
     * @return \Nesk\Puphpeteer\ElementHandle|null
     */
    public function waitForSelector(mixed $selector, array|null $options = NULL): mixed
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function windowId(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return list<\Nesk\Puphpeteer\WebWorker>
     */
    public function workers(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
