<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class SecurityDetails extends \Nesk\Puphpeteer\RemoteObject
{
    /**
     * @return string
     */
    public function issuer(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function protocol(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return list<string>
     */
    public function subjectAlternativeNames(): array
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function subjectName(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return int|float
     */
    public function validFrom(): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return int|float
     */
    public function validTo(): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
