<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class Target extends \Nesk\Puphpeteer\RemoteObject
{
    /**
     * @return \Nesk\Puphpeteer\Page
     */
    public function asPage(): \Nesk\Puphpeteer\Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return \Nesk\Puphpeteer\Browser
     */
    public function browser(): \Nesk\Puphpeteer\Browser
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return \Nesk\Puphpeteer\BrowserContext
     */
    public function browserContext(): \Nesk\Puphpeteer\BrowserContext
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return \Nesk\Puphpeteer\CDPSession
     */
    public function createCDPSession(): \Nesk\Puphpeteer\CDPSession
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|\Nesk\Puphpeteer\Target
     */
    public function opener(): null|\Nesk\Puphpeteer\Target
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|\Nesk\Puphpeteer\Page
     */
    public function page(): null|\Nesk\Puphpeteer\Page
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return "page"|"background_page"|"service_worker"|"shared_worker"|"browser"|"webview"|"other"
     */
    public function type(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function url(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|\Nesk\Puphpeteer\WebWorker
     */
    public function worker(): null|\Nesk\Puphpeteer\WebWorker
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
