<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class Tracing extends \Nesk\Puphpeteer\RemoteObject
{
    /**
     * @param (array{bufferSize?: int|float, categories?: list<string>, path?: string, screenshots?: bool})|null $options
     * @return void
     */
    public function start(array|null $options = NULL): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return null|string
     */
    public function stop(): null|string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
