<?php

// @generated by tools/upstream/update.cjs. Do not edit.

declare(strict_types=1);

namespace Nesk\Puphpeteer;

class WebWorker extends \Nesk\Puphpeteer\RemoteObject
{
    /**
     * @var \Nesk\Puphpeteer\CDPSession
     */
    public \Nesk\Puphpeteer\CDPSession $client {
        get {
            return $this->getRemote('client');
        }
    }
    /**
     * @return void
     */
    public function close(): void
    {
        $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string|\Nesk\Puphpeteer\JsFunction $func
     * @param mixed ...$args
     * @return mixed
     */
    public function evaluate(string|\Nesk\Puphpeteer\JsFunction $func, mixed ...$args): mixed
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }
    /**
     * @param string|\Nesk\Puphpeteer\JsFunction $func
     * @param mixed ...$args
     * @return \Nesk\Puphpeteer\JSHandle
     */
    public function evaluateHandle(string|\Nesk\Puphpeteer\JsFunction $func, mixed ...$args): \Nesk\Puphpeteer\JSHandle
    {
        return $this->invokeRemote(__FUNCTION__, self::mergeNamedArguments(func_get_args(), $args));
    }
    /**
     * @param string $type
     * @return int|float
     */
    public function listenerCount(string $type): int|float
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @param (\Closure|\Nesk\Puphpeteer\JsFunction)|null $handler
     * @return \Nesk\Puphpeteer\WebWorker
     */
    public function off(string $type, \Closure|\Nesk\Puphpeteer\JsFunction|null $handler = NULL): \Nesk\Puphpeteer\WebWorker
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @param \Closure|\Nesk\Puphpeteer\JsFunction $handler
     * @return \Nesk\Puphpeteer\WebWorker
     */
    public function on(string $type, \Closure|\Nesk\Puphpeteer\JsFunction $handler): \Nesk\Puphpeteer\WebWorker
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param string $type
     * @param \Closure|\Nesk\Puphpeteer\JsFunction $handler
     * @return \Nesk\Puphpeteer\WebWorker
     */
    public function once(string $type, \Closure|\Nesk\Puphpeteer\JsFunction $handler): \Nesk\Puphpeteer\WebWorker
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @param (string)|null $type
     * @return \Nesk\Puphpeteer\WebWorker
     */
    public function removeAllListeners(string|null $type = NULL): \Nesk\Puphpeteer\WebWorker
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
    /**
     * @return string
     */
    public function url(): string
    {
        return $this->invokeRemote(__FUNCTION__, func_get_args());
    }
}
